apiRules:
- include:
    uidRegex: ^rwby
    type: Namespace
- include:
    uidRegex: ^rwby\.editor
    type: Namespace
- include:
    uidRegex: ^Quantum
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
- exclude:
    uidRegex: ^Quantum\.Core
    type: Namespace
- exclude:
    uidRegex: ^Quantum\.BotSDK
    type: Namespace
- exclude:
    uidRegex: ^Quantum\.Task
    type: Namespace