apiRules:
- include:
    uidRegex: ^rwby
    type: Namespace
- include:
    uidRegex: ^rwby\.editor
    type: Namespace
- include:
    uidRegex: ^Quantum\.Simulation
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace