### YamlMime:ManagedReference
items:
- uid: Global.GamemodeTeamTypeConfig
  commentId: T:Global.GamemodeTeamTypeConfig
  id: GamemodeTeamTypeConfig
  parent: Global
  children:
  - Global.GamemodeTeamTypeConfig.maximumOfType
  - Global.GamemodeTeamTypeConfig.maximumPlayers
  - Global.GamemodeTeamTypeConfig.minimumOfType
  - Global.GamemodeTeamTypeConfig.minimumPlayers
  - Global.GamemodeTeamTypeConfig.name
  langs:
  - csharp
  - vb
  name: GamemodeTeamTypeConfig
  nameWithType: GamemodeTeamTypeConfig
  fullName: GamemodeTeamTypeConfig
  type: Struct
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GamemodeTeamTypeConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 12
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: >-
      [Serializable]

      public struct GamemodeTeamTypeConfig
    content.vb: >-
      <Serializable>

      Public Structure GamemodeTeamTypeConfig
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Global.GamemodeTeamTypeConfig.name
  commentId: F:Global.GamemodeTeamTypeConfig.name
  id: name
  parent: Global.GamemodeTeamTypeConfig
  langs:
  - csharp
  - vb
  name: name
  nameWithType: GamemodeTeamTypeConfig.name
  fullName: GamemodeTeamTypeConfig.name
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: name
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 15
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public string name
    return:
      type: System.String
    content.vb: Public name As String
- uid: Global.GamemodeTeamTypeConfig.minimumOfType
  commentId: F:Global.GamemodeTeamTypeConfig.minimumOfType
  id: minimumOfType
  parent: Global.GamemodeTeamTypeConfig
  langs:
  - csharp
  - vb
  name: minimumOfType
  nameWithType: GamemodeTeamTypeConfig.minimumOfType
  fullName: GamemodeTeamTypeConfig.minimumOfType
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: minimumOfType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 16
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public int minimumOfType
    return:
      type: System.Int32
    content.vb: Public minimumOfType As Integer
- uid: Global.GamemodeTeamTypeConfig.maximumOfType
  commentId: F:Global.GamemodeTeamTypeConfig.maximumOfType
  id: maximumOfType
  parent: Global.GamemodeTeamTypeConfig
  langs:
  - csharp
  - vb
  name: maximumOfType
  nameWithType: GamemodeTeamTypeConfig.maximumOfType
  fullName: GamemodeTeamTypeConfig.maximumOfType
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: maximumOfType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 17
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public int maximumOfType
    return:
      type: System.Int32
    content.vb: Public maximumOfType As Integer
- uid: Global.GamemodeTeamTypeConfig.minimumPlayers
  commentId: F:Global.GamemodeTeamTypeConfig.minimumPlayers
  id: minimumPlayers
  parent: Global.GamemodeTeamTypeConfig
  langs:
  - csharp
  - vb
  name: minimumPlayers
  nameWithType: GamemodeTeamTypeConfig.minimumPlayers
  fullName: GamemodeTeamTypeConfig.minimumPlayers
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: minimumPlayers
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 18
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public int minimumPlayers
    return:
      type: System.Int32
    content.vb: Public minimumPlayers As Integer
- uid: Global.GamemodeTeamTypeConfig.maximumPlayers
  commentId: F:Global.GamemodeTeamTypeConfig.maximumPlayers
  id: maximumPlayers
  parent: Global.GamemodeTeamTypeConfig
  langs:
  - csharp
  - vb
  name: maximumPlayers
  nameWithType: GamemodeTeamTypeConfig.maximumPlayers
  fullName: GamemodeTeamTypeConfig.maximumPlayers
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: maximumPlayers
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 19
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public int maximumPlayers
    return:
      type: System.Int32
    content.vb: Public maximumPlayers As Integer
references:
- uid: Global
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
