### YamlMime:ManagedReference
items:
- uid: Global.GamemodeTeamConfig
  commentId: T:Global.GamemodeTeamConfig
  id: GamemodeTeamConfig
  parent: Global
  children:
  - Global.GamemodeTeamConfig.color
  - Global.GamemodeTeamConfig.name
  - Global.GamemodeTeamConfig.removeable
  - Global.GamemodeTeamConfig.teamTypeId
  langs:
  - csharp
  - vb
  name: GamemodeTeamConfig
  nameWithType: GamemodeTeamConfig
  fullName: GamemodeTeamConfig
  type: Struct
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GamemodeTeamConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 2
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: >-
      [Serializable]

      public struct GamemodeTeamConfig
    content.vb: >-
      <Serializable>

      Public Structure GamemodeTeamConfig
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Global.GamemodeTeamConfig.name
  commentId: F:Global.GamemodeTeamConfig.name
  id: name
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: name
  nameWithType: GamemodeTeamConfig.name
  fullName: GamemodeTeamConfig.name
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: name
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 5
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public string name
    return:
      type: System.String
    content.vb: Public name As String
- uid: Global.GamemodeTeamConfig.color
  commentId: F:Global.GamemodeTeamConfig.color
  id: color
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: color
  nameWithType: GamemodeTeamConfig.color
  fullName: GamemodeTeamConfig.color
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: color
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 6
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public Color color
    return:
      type: UnityEngine.Color
    content.vb: Public color As Color
- uid: Global.GamemodeTeamConfig.teamTypeId
  commentId: F:Global.GamemodeTeamConfig.teamTypeId
  id: teamTypeId
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: teamTypeId
  nameWithType: GamemodeTeamConfig.teamTypeId
  fullName: GamemodeTeamConfig.teamTypeId
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: teamTypeId
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 7
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public int teamTypeId
    return:
      type: System.Int32
    content.vb: Public teamTypeId As Integer
- uid: Global.GamemodeTeamConfig.removeable
  commentId: F:Global.GamemodeTeamConfig.removeable
  id: removeable
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: removeable
  nameWithType: GamemodeTeamConfig.removeable
  fullName: GamemodeTeamConfig.removeable
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: removeable
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/GamemodeTeamConfig.cs
    startLine: 8
  assemblies:
  - Quantum.Simulation
  namespace: Global
  syntax:
    content: public bool removeable
    return:
      type: System.Boolean
    content.vb: Public removeable As Boolean
references:
- uid: Global
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine.Color
  commentId: T:UnityEngine.Color
  parent: UnityEngine
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: UnityEngine.Color
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
