### YamlMime:ManagedReference
items:
- uid: Global.GamemodeTeamConfig
  commentId: T:Global.GamemodeTeamConfig
  id: GamemodeTeamConfig
  parent: Global
  children:
  - Global.GamemodeTeamConfig.maximumPlayers
  - Global.GamemodeTeamConfig.minimumPlayers
  - Global.GamemodeTeamConfig.name
  langs:
  - csharp
  - vb
  name: GamemodeTeamConfig
  nameWithType: GamemodeTeamConfig
  fullName: GamemodeTeamConfig
  type: Struct
  source:
    remote:
      path: rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GamemodeTeamConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
  assemblies:
  - rwby
  namespace: Global
  syntax:
    content: >-
      [Serializable]

      public struct GamemodeTeamConfig
    content.vb: >-
      <Serializable>

      Public Structure GamemodeTeamConfig
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Global.GamemodeTeamConfig.name
  commentId: F:Global.GamemodeTeamConfig.name
  id: name
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: name
  nameWithType: GamemodeTeamConfig.name
  fullName: GamemodeTeamConfig.name
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: name
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
    startLine: 3
  assemblies:
  - rwby
  namespace: Global
  syntax:
    content: public string name
    return:
      type: System.String
    content.vb: Public name As String
- uid: Global.GamemodeTeamConfig.minimumPlayers
  commentId: F:Global.GamemodeTeamConfig.minimumPlayers
  id: minimumPlayers
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: minimumPlayers
  nameWithType: GamemodeTeamConfig.minimumPlayers
  fullName: GamemodeTeamConfig.minimumPlayers
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: minimumPlayers
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
    startLine: 4
  assemblies:
  - rwby
  namespace: Global
  syntax:
    content: public int minimumPlayers
    return:
      type: System.Int32
    content.vb: Public minimumPlayers As Integer
- uid: Global.GamemodeTeamConfig.maximumPlayers
  commentId: F:Global.GamemodeTeamConfig.maximumPlayers
  id: maximumPlayers
  parent: Global.GamemodeTeamConfig
  langs:
  - csharp
  - vb
  name: maximumPlayers
  nameWithType: GamemodeTeamConfig.maximumPlayers
  fullName: GamemodeTeamConfig.maximumPlayers
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: maximumPlayers
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/1.Project/Scripts/Content/Gamemodes/GamemodeTeamConfig.cs
    startLine: 5
  assemblies:
  - rwby
  namespace: Global
  syntax:
    content: public int maximumPlayers
    return:
      type: System.Int32
    content.vb: Public maximumPlayers As Integer
references:
- uid: Global
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
