### YamlMime:ManagedReference
items:
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions
  commentId: T:Quantum.SimulationConfigChecksumErrorDumpOptions
  id: SimulationConfigChecksumErrorDumpOptions
  parent: Quantum
  children:
  - Quantum.SimulationConfigChecksumErrorDumpOptions.ComponentChecksums
  - Quantum.SimulationConfigChecksumErrorDumpOptions.RawFPValues
  - Quantum.SimulationConfigChecksumErrorDumpOptions.ReadableDynamicDB
  - Quantum.SimulationConfigChecksumErrorDumpOptions.SendAssetDBChecksums
  langs:
  - csharp
  - vb
  name: SimulationConfigChecksumErrorDumpOptions
  nameWithType: SimulationConfigChecksumErrorDumpOptions
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: SimulationConfigChecksumErrorDumpOptions
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 246
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Configuration options for checksum error dumps.
  example: []
  syntax:
    content: >-
      [Flags]

      public enum SimulationConfigChecksumErrorDumpOptions
    content.vb: >-
      <Flags>

      Public Enum SimulationConfigChecksumErrorDumpOptions
  attributes:
  - type: System.FlagsAttribute
    ctor: System.FlagsAttribute.#ctor
    arguments: []
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions.SendAssetDBChecksums
  commentId: F:Quantum.SimulationConfigChecksumErrorDumpOptions.SendAssetDBChecksums
  id: SendAssetDBChecksums
  parent: Quantum.SimulationConfigChecksumErrorDumpOptions
  langs:
  - csharp
  - vb
  name: SendAssetDBChecksums
  nameWithType: SimulationConfigChecksumErrorDumpOptions.SendAssetDBChecksums
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions.SendAssetDBChecksums
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: SendAssetDBChecksums
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 251
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Sends asset db checksums.
  example: []
  syntax:
    content: SendAssetDBChecksums = 1
    return:
      type: Quantum.SimulationConfigChecksumErrorDumpOptions
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions.ReadableDynamicDB
  commentId: F:Quantum.SimulationConfigChecksumErrorDumpOptions.ReadableDynamicDB
  id: ReadableDynamicDB
  parent: Quantum.SimulationConfigChecksumErrorDumpOptions
  langs:
  - csharp
  - vb
  name: ReadableDynamicDB
  nameWithType: SimulationConfigChecksumErrorDumpOptions.ReadableDynamicDB
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions.ReadableDynamicDB
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: ReadableDynamicDB
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 255
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Dumps readable information from the dynamic db.
  example: []
  syntax:
    content: ReadableDynamicDB = 2
    return:
      type: Quantum.SimulationConfigChecksumErrorDumpOptions
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions.RawFPValues
  commentId: F:Quantum.SimulationConfigChecksumErrorDumpOptions.RawFPValues
  id: RawFPValues
  parent: Quantum.SimulationConfigChecksumErrorDumpOptions
  langs:
  - csharp
  - vb
  name: RawFPValues
  nameWithType: SimulationConfigChecksumErrorDumpOptions.RawFPValues
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions.RawFPValues
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: RawFPValues
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 259
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Prints raw FP values.
  example: []
  syntax:
    content: RawFPValues = 4
    return:
      type: Quantum.SimulationConfigChecksumErrorDumpOptions
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions.ComponentChecksums
  commentId: F:Quantum.SimulationConfigChecksumErrorDumpOptions.ComponentChecksums
  id: ComponentChecksums
  parent: Quantum.SimulationConfigChecksumErrorDumpOptions
  langs:
  - csharp
  - vb
  name: ComponentChecksums
  nameWithType: SimulationConfigChecksumErrorDumpOptions.ComponentChecksums
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions.ComponentChecksums
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: ComponentChecksums
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 263
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Dumps component checksums.
  example: []
  syntax:
    content: ComponentChecksums = 8
    return:
      type: Quantum.SimulationConfigChecksumErrorDumpOptions
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.SimulationConfigChecksumErrorDumpOptions
  commentId: T:Quantum.SimulationConfigChecksumErrorDumpOptions
  parent: Quantum
  href: Quantum.SimulationConfigChecksumErrorDumpOptions.html
  name: SimulationConfigChecksumErrorDumpOptions
  nameWithType: SimulationConfigChecksumErrorDumpOptions
  fullName: Quantum.SimulationConfigChecksumErrorDumpOptions
