### YamlMime:ManagedReference
items:
- uid: Quantum.HNSFConfig.KeyValuePair
  commentId: T:Quantum.HNSFConfig.KeyValuePair
  id: HNSFConfig.KeyValuePair
  parent: Quantum
  children:
  - Quantum.HNSFConfig.KeyValuePair.Key
  - Quantum.HNSFConfig.KeyValuePair.Type
  - Quantum.HNSFConfig.KeyValuePair.Value
  langs:
  - csharp
  - vb
  name: HNSFConfig.KeyValuePair
  nameWithType: HNSFConfig.KeyValuePair
  fullName: Quantum.HNSFConfig.KeyValuePair
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: KeyValuePair
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 22
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: >-
      [Serializable]

      public class HNSFConfig.KeyValuePair
    content.vb: >-
      <Serializable>

      Public Class HNSFConfig.KeyValuePair
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Quantum.HNSFConfig.KeyValuePair.Key
  commentId: F:Quantum.HNSFConfig.KeyValuePair.Key
  id: Key
  parent: Quantum.HNSFConfig.KeyValuePair
  langs:
  - csharp
  - vb
  name: Key
  nameWithType: HNSFConfig.KeyValuePair.Key
  fullName: Quantum.HNSFConfig.KeyValuePair.Key
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Key
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 25
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public string Key
    return:
      type: System.String
    content.vb: Public Key As String
- uid: Quantum.HNSFConfig.KeyValuePair.Type
  commentId: F:Quantum.HNSFConfig.KeyValuePair.Type
  id: Type
  parent: Quantum.HNSFConfig.KeyValuePair
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: HNSFConfig.KeyValuePair.Type
  fullName: Quantum.HNSFConfig.KeyValuePair.Type
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Type
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 26
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public HNSFConfig.EValueType Type
    return:
      type: Quantum.HNSFConfig.EValueType
    content.vb: Public Type As HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.KeyValuePair.Value
  commentId: F:Quantum.HNSFConfig.KeyValuePair.Value
  id: Value
  parent: Quantum.HNSFConfig.KeyValuePair
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: HNSFConfig.KeyValuePair.Value
  fullName: Quantum.HNSFConfig.KeyValuePair.Value
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Value
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 27
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public HNSFConfig.Value Value
    return:
      type: Quantum.HNSFConfig.Value
    content.vb: Public Value As HNSFConfig.Value
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quantum.HNSFConfig.EValueType
  commentId: T:Quantum.HNSFConfig.EValueType
  parent: Quantum
  href: Quantum.HNSFConfig.html
  name: HNSFConfig.EValueType
  nameWithType: HNSFConfig.EValueType
  fullName: Quantum.HNSFConfig.EValueType
  spec.csharp:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.EValueType
    name: EValueType
    href: Quantum.HNSFConfig.EValueType.html
  spec.vb:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.EValueType
    name: EValueType
    href: Quantum.HNSFConfig.EValueType.html
- uid: Quantum.HNSFConfig.Value
  commentId: T:Quantum.HNSFConfig.Value
  parent: Quantum
  href: Quantum.HNSFConfig.html
  name: HNSFConfig.Value
  nameWithType: HNSFConfig.Value
  fullName: Quantum.HNSFConfig.Value
  spec.csharp:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.Value
    name: Value
    href: Quantum.HNSFConfig.Value.html
  spec.vb:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.Value
    name: Value
    href: Quantum.HNSFConfig.Value.html
