### YamlMime:ManagedReference
items:
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType
  commentId: T:Quantum.GetDummyConfigAIFunction.DummyEnumType
  id: GetDummyConfigAIFunction.DummyEnumType
  parent: Quantum
  children:
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.behaviour
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.blockBehaviour
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.blockDirection
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.controlType
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.counterhit
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.framesBeforeGroundRecovery
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.framesToHoldBlockAfterBlockstunEnded
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.groundRecovery
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.hitsBeforeShouldBlock
  - Quantum.GetDummyConfigAIFunction.DummyEnumType.throwEscape
  langs:
  - csharp
  - vb
  name: GetDummyConfigAIFunction.DummyEnumType
  nameWithType: GetDummyConfigAIFunction.DummyEnumType
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: DummyEnumType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 5
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public enum GetDummyConfigAIFunction.DummyEnumType
    content.vb: Public Enum GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.controlType
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.controlType
  id: controlType
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: controlType
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.controlType
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.controlType
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: controlType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 7
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: controlType = 0
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.behaviour
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.behaviour
  id: behaviour
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: behaviour
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.behaviour
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.behaviour
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: behaviour
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 8
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: behaviour = 1
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.counterhit
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.counterhit
  id: counterhit
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: counterhit
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.counterhit
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.counterhit
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: counterhit
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 9
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: counterhit = 2
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.blockBehaviour
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.blockBehaviour
  id: blockBehaviour
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: blockBehaviour
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.blockBehaviour
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.blockBehaviour
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: blockBehaviour
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 10
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: blockBehaviour = 3
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.hitsBeforeShouldBlock
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.hitsBeforeShouldBlock
  id: hitsBeforeShouldBlock
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: hitsBeforeShouldBlock
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.hitsBeforeShouldBlock
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.hitsBeforeShouldBlock
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: hitsBeforeShouldBlock
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 11
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: hitsBeforeShouldBlock = 4
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.framesToHoldBlockAfterBlockstunEnded
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.framesToHoldBlockAfterBlockstunEnded
  id: framesToHoldBlockAfterBlockstunEnded
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: framesToHoldBlockAfterBlockstunEnded
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.framesToHoldBlockAfterBlockstunEnded
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.framesToHoldBlockAfterBlockstunEnded
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: framesToHoldBlockAfterBlockstunEnded
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 12
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: framesToHoldBlockAfterBlockstunEnded = 5
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.blockDirection
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.blockDirection
  id: blockDirection
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: blockDirection
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.blockDirection
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.blockDirection
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: blockDirection
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 13
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: blockDirection = 6
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.throwEscape
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.throwEscape
  id: throwEscape
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: throwEscape
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.throwEscape
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.throwEscape
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: throwEscape
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 14
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: throwEscape = 7
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.groundRecovery
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.groundRecovery
  id: groundRecovery
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: groundRecovery
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.groundRecovery
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.groundRecovery
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: groundRecovery
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 15
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: groundRecovery = 8
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType.framesBeforeGroundRecovery
  commentId: F:Quantum.GetDummyConfigAIFunction.DummyEnumType.framesBeforeGroundRecovery
  id: framesBeforeGroundRecovery
  parent: Quantum.GetDummyConfigAIFunction.DummyEnumType
  langs:
  - csharp
  - vb
  name: framesBeforeGroundRecovery
  nameWithType: GetDummyConfigAIFunction.DummyEnumType.framesBeforeGroundRecovery
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType.framesBeforeGroundRecovery
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: framesBeforeGroundRecovery
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/AI/GetDummyConfigAIFunction.cs
    startLine: 16
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: framesBeforeGroundRecovery = 9
    return:
      type: Quantum.GetDummyConfigAIFunction.DummyEnumType
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.GetDummyConfigAIFunction.DummyEnumType
  commentId: T:Quantum.GetDummyConfigAIFunction.DummyEnumType
  parent: Quantum
  href: Quantum.GetDummyConfigAIFunction.html
  name: GetDummyConfigAIFunction.DummyEnumType
  nameWithType: GetDummyConfigAIFunction.DummyEnumType
  fullName: Quantum.GetDummyConfigAIFunction.DummyEnumType
  spec.csharp:
  - uid: Quantum.GetDummyConfigAIFunction
    name: GetDummyConfigAIFunction
    href: Quantum.GetDummyConfigAIFunction.html
  - name: .
  - uid: Quantum.GetDummyConfigAIFunction.DummyEnumType
    name: DummyEnumType
    href: Quantum.GetDummyConfigAIFunction.DummyEnumType.html
  spec.vb:
  - uid: Quantum.GetDummyConfigAIFunction
    name: GetDummyConfigAIFunction
    href: Quantum.GetDummyConfigAIFunction.html
  - name: .
  - uid: Quantum.GetDummyConfigAIFunction.DummyEnumType
    name: DummyEnumType
    href: Quantum.GetDummyConfigAIFunction.DummyEnumType.html
