### YamlMime:ManagedReference
items:
- uid: Quantum.HNSFConfig.Value
  commentId: T:Quantum.HNSFConfig.Value
  id: HNSFConfig.Value
  parent: Quantum
  children:
  - Quantum.HNSFConfig.Value.AssetRef
  - Quantum.HNSFConfig.Value.Boolean
  - Quantum.HNSFConfig.Value.Byte
  - Quantum.HNSFConfig.Value.EntityRef
  - Quantum.HNSFConfig.Value.FP
  - Quantum.HNSFConfig.Value.FPVector2
  - Quantum.HNSFConfig.Value.FPVector3
  - Quantum.HNSFConfig.Value.Integer
  - Quantum.HNSFConfig.Value.String
  langs:
  - csharp
  - vb
  name: HNSFConfig.Value
  nameWithType: HNSFConfig.Value
  fullName: Quantum.HNSFConfig.Value
  type: Struct
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Value
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 30
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: >-
      [Serializable]

      public struct HNSFConfig.Value
    content.vb: >-
      <Serializable>

      Public Structure HNSFConfig.Value
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Quantum.HNSFConfig.Value.Integer
  commentId: F:Quantum.HNSFConfig.Value.Integer
  id: Integer
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: Integer
  nameWithType: HNSFConfig.Value.Integer
  fullName: Quantum.HNSFConfig.Value.Integer
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Integer
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 33
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public int Integer
    return:
      type: System.Int32
    content.vb: Public [Integer] As Integer
- uid: Quantum.HNSFConfig.Value.Boolean
  commentId: F:Quantum.HNSFConfig.Value.Boolean
  id: Boolean
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: Boolean
  nameWithType: HNSFConfig.Value.Boolean
  fullName: Quantum.HNSFConfig.Value.Boolean
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Boolean
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 34
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public bool Boolean
    return:
      type: System.Boolean
    content.vb: Public [Boolean] As Boolean
- uid: Quantum.HNSFConfig.Value.Byte
  commentId: F:Quantum.HNSFConfig.Value.Byte
  id: Byte
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: Byte
  nameWithType: HNSFConfig.Value.Byte
  fullName: Quantum.HNSFConfig.Value.Byte
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Byte
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 35
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public byte Byte
    return:
      type: System.Byte
    content.vb: Public [Byte] As Byte
- uid: Quantum.HNSFConfig.Value.FP
  commentId: F:Quantum.HNSFConfig.Value.FP
  id: FP
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: FP
  nameWithType: HNSFConfig.Value.FP
  fullName: Quantum.HNSFConfig.Value.FP
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FP
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 36
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public FP FP
    return:
      type: Photon.Deterministic.FP
    content.vb: Public FP As FP
- uid: Quantum.HNSFConfig.Value.FPVector2
  commentId: F:Quantum.HNSFConfig.Value.FPVector2
  id: FPVector2
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: FPVector2
  nameWithType: HNSFConfig.Value.FPVector2
  fullName: Quantum.HNSFConfig.Value.FPVector2
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FPVector2
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 37
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public FPVector2 FPVector2
    return:
      type: Photon.Deterministic.FPVector2
    content.vb: Public FPVector2 As FPVector2
- uid: Quantum.HNSFConfig.Value.FPVector3
  commentId: F:Quantum.HNSFConfig.Value.FPVector3
  id: FPVector3
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: FPVector3
  nameWithType: HNSFConfig.Value.FPVector3
  fullName: Quantum.HNSFConfig.Value.FPVector3
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FPVector3
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 38
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public FPVector3 FPVector3
    return:
      type: Photon.Deterministic.FPVector3
    content.vb: Public FPVector3 As FPVector3
- uid: Quantum.HNSFConfig.Value.String
  commentId: F:Quantum.HNSFConfig.Value.String
  id: String
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: String
  nameWithType: HNSFConfig.Value.String
  fullName: Quantum.HNSFConfig.Value.String
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: String
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 39
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public string String
    return:
      type: System.String
    content.vb: Public [String] As String
- uid: Quantum.HNSFConfig.Value.EntityRef
  commentId: F:Quantum.HNSFConfig.Value.EntityRef
  id: EntityRef
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: EntityRef
  nameWithType: HNSFConfig.Value.EntityRef
  fullName: Quantum.HNSFConfig.Value.EntityRef
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: EntityRef
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 40
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public EntityRef EntityRef
    return:
      type: Quantum.EntityRef
    content.vb: Public EntityRef As EntityRef
- uid: Quantum.HNSFConfig.Value.AssetRef
  commentId: F:Quantum.HNSFConfig.Value.AssetRef
  id: AssetRef
  parent: Quantum.HNSFConfig.Value
  langs:
  - csharp
  - vb
  name: AssetRef
  nameWithType: HNSFConfig.Value.AssetRef
  fullName: Quantum.HNSFConfig.Value.AssetRef
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AssetRef
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 41
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public AssetRef AssetRef
    return:
      type: Quantum.AssetRef
    content.vb: Public AssetRef As AssetRef
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: Photon.Deterministic.FP
  commentId: T:Photon.Deterministic.FP
  parent: Photon.Deterministic
  isExternal: true
  name: FP
  nameWithType: FP
  fullName: Photon.Deterministic.FP
- uid: Photon.Deterministic
  commentId: N:Photon.Deterministic
  isExternal: true
  name: Photon.Deterministic
  nameWithType: Photon.Deterministic
  fullName: Photon.Deterministic
  spec.csharp:
  - uid: Photon
    name: Photon
    isExternal: true
  - name: .
  - uid: Photon.Deterministic
    name: Deterministic
    isExternal: true
  spec.vb:
  - uid: Photon
    name: Photon
    isExternal: true
  - name: .
  - uid: Photon.Deterministic
    name: Deterministic
    isExternal: true
- uid: Photon.Deterministic.FPVector2
  commentId: T:Photon.Deterministic.FPVector2
  parent: Photon.Deterministic
  isExternal: true
  name: FPVector2
  nameWithType: FPVector2
  fullName: Photon.Deterministic.FPVector2
- uid: Photon.Deterministic.FPVector3
  commentId: T:Photon.Deterministic.FPVector3
  parent: Photon.Deterministic
  isExternal: true
  name: FPVector3
  nameWithType: FPVector3
  fullName: Photon.Deterministic.FPVector3
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quantum.EntityRef
  commentId: T:Quantum.EntityRef
  parent: Quantum
  isExternal: true
  name: EntityRef
  nameWithType: EntityRef
  fullName: Quantum.EntityRef
- uid: Quantum.AssetRef
  commentId: T:Quantum.AssetRef
  parent: Quantum
  isExternal: true
  name: AssetRef
  nameWithType: AssetRef
  fullName: Quantum.AssetRef
