### YamlMime:ManagedReference
items:
- uid: Quantum.AIBotComboConfig
  commentId: T:Quantum.AIBotComboConfig
  id: AIBotComboConfig
  parent: Quantum
  children:
  - Quantum.AIBotComboConfig.combos
  langs:
  - csharp
  - vb
  name: AIBotComboConfig
  nameWithType: AIBotComboConfig
  fullName: Quantum.AIBotComboConfig
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/AI/Fighter/AIBotComboConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AIBotComboConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/AI/Fighter/AIBotComboConfig.cs
    startLine: 2
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: >-
      [Serializable]

      public class AIBotComboConfig
    content.vb: >-
      <Serializable>

      Public Class AIBotComboConfig
  inheritance:
  - System.Object
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Quantum.AIBotComboConfig.combos
  commentId: F:Quantum.AIBotComboConfig.combos
  id: combos
  parent: Quantum.AIBotComboConfig
  langs:
  - csharp
  - vb
  name: combos
  nameWithType: AIBotComboConfig.combos
  fullName: Quantum.AIBotComboConfig.combos
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/AI/Fighter/AIBotComboConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: combos
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/AI/Fighter/AIBotComboConfig.cs
    startLine: 5
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public AssetRef<AIBotComboEntry>[] combos
    return:
      type: Quantum.AssetRef{Quantum.AIBotComboEntry}[]
    content.vb: Public combos As AssetRef(Of AIBotComboEntry)()
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quantum.AssetRef{Quantum.AIBotComboEntry}[]
  isExternal: true
  href: Quantum.AIBotComboEntry.html
  name: AssetRef<AIBotComboEntry>[]
  nameWithType: AssetRef<AIBotComboEntry>[]
  fullName: Quantum.AssetRef<Quantum.AIBotComboEntry>[]
  nameWithType.vb: AssetRef(Of AIBotComboEntry)()
  fullName.vb: Quantum.AssetRef(Of Quantum.AIBotComboEntry)()
  name.vb: AssetRef(Of AIBotComboEntry)()
  spec.csharp:
  - uid: Quantum.AssetRef`1
    name: AssetRef
    isExternal: true
  - name: <
  - uid: Quantum.AIBotComboEntry
    name: AIBotComboEntry
    href: Quantum.AIBotComboEntry.html
  - name: '>'
  - name: '['
  - name: ']'
  spec.vb:
  - uid: Quantum.AssetRef`1
    name: AssetRef
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Quantum.AIBotComboEntry
    name: AIBotComboEntry
    href: Quantum.AIBotComboEntry.html
  - name: )
  - name: (
  - name: )
