### YamlMime:ManagedReference
items:
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  commentId: T:Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  id: SimulationConfig.AutoLoadSceneFromMapMode
  parent: Quantum
  children:
  - Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Disabled
  - Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Legacy
  - Quantum.SimulationConfig.AutoLoadSceneFromMapMode.LoadThenUnloadPreviousScene
  - Quantum.SimulationConfig.AutoLoadSceneFromMapMode.UnloadPreviousSceneThenLoad
  langs:
  - csharp
  - vb
  name: SimulationConfig.AutoLoadSceneFromMapMode
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AutoLoadSceneFromMapMode
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 26
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: >-
    The scene load mode to use when changing Quantum maps.

    <p>Will trigger for example for the initial map that is set in Quantum by <xref href="Quantum.RuntimeConfig.Map" data-throw-if-not-resolved="false"></xref> and on subsequent map changes.</p><p>The Unity scene referenced by <xref href="Quantum.Map.Scene" data-throw-if-not-resolved="false"></xref> will be loaded.</p>
  example: []
  syntax:
    content: public enum SimulationConfig.AutoLoadSceneFromMapMode
    content.vb: Public Enum SimulationConfig.AutoLoadSceneFromMapMode
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Disabled
  commentId: F:Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Disabled
  id: Disabled
  parent: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  langs:
  - csharp
  - vb
  name: Disabled
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode.Disabled
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Disabled
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Disabled
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 30
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Automatic scene loading disabled.
  example: []
  syntax:
    content: Disabled = 0
    return:
      type: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Legacy
  commentId: F:Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Legacy
  id: Legacy
  parent: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  langs:
  - csharp
  - vb
  name: Legacy
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode.Legacy
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.Legacy
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Legacy
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 34
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: 'Obsolete: unused.'
  example: []
  syntax:
    content: >-
      [Obsolete]

      Legacy = 1
    return:
      type: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
    content.vb: >-
      <Obsolete>

      Legacy = 1
  attributes:
  - type: System.ObsoleteAttribute
    ctor: System.ObsoleteAttribute.#ctor
    arguments: []
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.UnloadPreviousSceneThenLoad
  commentId: F:Quantum.SimulationConfig.AutoLoadSceneFromMapMode.UnloadPreviousSceneThenLoad
  id: UnloadPreviousSceneThenLoad
  parent: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  langs:
  - csharp
  - vb
  name: UnloadPreviousSceneThenLoad
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode.UnloadPreviousSceneThenLoad
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.UnloadPreviousSceneThenLoad
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: UnloadPreviousSceneThenLoad
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 39
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Unload the current scene then load the new scene.
  example: []
  syntax:
    content: UnloadPreviousSceneThenLoad = 2
    return:
      type: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.LoadThenUnloadPreviousScene
  commentId: F:Quantum.SimulationConfig.AutoLoadSceneFromMapMode.LoadThenUnloadPreviousScene
  id: LoadThenUnloadPreviousScene
  parent: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  langs:
  - csharp
  - vb
  name: LoadThenUnloadPreviousScene
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode.LoadThenUnloadPreviousScene
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.LoadThenUnloadPreviousScene
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: LoadThenUnloadPreviousScene
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SimulationConfig.cs
    startLine: 43
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Load the new scene then unload the current scene.
  example: []
  syntax:
    content: LoadThenUnloadPreviousScene = 3
    return:
      type: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
references:
- uid: Quantum.RuntimeConfig.Map
  commentId: F:Quantum.RuntimeConfig.Map
  href: Quantum.RuntimeConfig.html#Quantum_RuntimeConfig_Map
  name: Map
  nameWithType: RuntimeConfig.Map
  fullName: Quantum.RuntimeConfig.Map
- uid: Quantum.Map.Scene
  commentId: F:Quantum.Map.Scene
  isExternal: true
  name: Scene
  nameWithType: Map.Scene
  fullName: Quantum.Map.Scene
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  commentId: T:Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  parent: Quantum
  href: Quantum.SimulationConfig.html
  name: SimulationConfig.AutoLoadSceneFromMapMode
  nameWithType: SimulationConfig.AutoLoadSceneFromMapMode
  fullName: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
  spec.csharp:
  - uid: Quantum.SimulationConfig
    name: SimulationConfig
    href: Quantum.SimulationConfig.html
  - name: .
  - uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
    name: AutoLoadSceneFromMapMode
    href: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.html
  spec.vb:
  - uid: Quantum.SimulationConfig
    name: SimulationConfig
    href: Quantum.SimulationConfig.html
  - name: .
  - uid: Quantum.SimulationConfig.AutoLoadSceneFromMapMode
    name: AutoLoadSceneFromMapMode
    href: Quantum.SimulationConfig.AutoLoadSceneFromMapMode.html
