### YamlMime:ManagedReference
items:
- uid: Quantum.SystemsConfig.SystemEntry
  commentId: T:Quantum.SystemsConfig.SystemEntry
  id: SystemsConfig.SystemEntry
  parent: Quantum
  children: []
  langs:
  - csharp
  - vb
  name: SystemsConfig.SystemEntry
  nameWithType: SystemsConfig.SystemEntry
  fullName: Quantum.SystemsConfig.SystemEntry
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: SystemEntry
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
    startLine: 79
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Base system type.
  example: []
  syntax:
    content: >-
      [Serializable]

      public class SystemsConfig.SystemEntry : SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>
    content.vb: >-
      <Serializable>

      Public Class SystemsConfig.SystemEntry Inherits SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry)
  inheritance:
  - System.Object
  - Quantum.SystemsConfig.SystemEntryBase
  - Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  inheritedMembers:
  - Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.Children
  - Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.GetChildren
  - Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.AddSystem``1(System.String,System.Boolean)
  - Quantum.SystemsConfig.SystemEntryBase.SystemType
  - Quantum.SystemsConfig.SystemEntryBase.SystemName
  - Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Quantum.SystemsConfig.SystemEntryBase
  commentId: T:Quantum.SystemsConfig.SystemEntryBase
  parent: Quantum
  href: Quantum.SystemsConfig.html
  name: SystemsConfig.SystemEntryBase
  nameWithType: SystemsConfig.SystemEntryBase
  fullName: Quantum.SystemsConfig.SystemEntryBase
  spec.csharp:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
  spec.vb:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
- uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  commentId: T:Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  parent: Quantum
  definition: Quantum.SystemsConfig.SystemEntryBase`1
  href: Quantum.SystemsConfig.html
  name: SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>
  nameWithType: SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>
  fullName: Quantum.SystemsConfig.SystemEntryBase<Quantum.SystemsConfig.SubSystemEntry>
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry)
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of Quantum.SystemsConfig.SubSystemEntry)
  name.vb: SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry)
  spec.csharp:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase`1
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase-1.html
  - name: <
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SubSystemEntry
    name: SubSystemEntry
    href: Quantum.SystemsConfig.SubSystemEntry.html
  - name: '>'
  spec.vb:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase`1
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SubSystemEntry
    name: SubSystemEntry
    href: Quantum.SystemsConfig.SubSystemEntry.html
  - name: )
- uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.Children
  commentId: F:Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.Children
  parent: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  definition: Quantum.SystemsConfig.SystemEntryBase`1.Children
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_Children
  name: Children
  nameWithType: SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>.Children
  fullName: Quantum.SystemsConfig.SystemEntryBase<Quantum.SystemsConfig.SubSystemEntry>.Children
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry).Children
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of Quantum.SystemsConfig.SubSystemEntry).Children
- uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.GetChildren
  commentId: M:Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.GetChildren
  parent: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  definition: Quantum.SystemsConfig.SystemEntryBase`1.GetChildren
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  name: GetChildren()
  nameWithType: SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>.GetChildren()
  fullName: Quantum.SystemsConfig.SystemEntryBase<Quantum.SystemsConfig.SubSystemEntry>.GetChildren()
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry).GetChildren()
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of Quantum.SystemsConfig.SubSystemEntry).GetChildren()
  spec.csharp:
  - uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  - name: (
  - name: )
  spec.vb:
  - uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  - name: (
  - name: )
- uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.AddSystem``1(System.String,System.Boolean)
  commentId: M:Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.AddSystem``1(System.String,System.Boolean)
  parent: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}
  definition: Quantum.SystemsConfig.SystemEntryBase`1.AddSystem``1(System.String,System.Boolean)
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  name: AddSystem<TSystem>(string, bool)
  nameWithType: SystemsConfig.SystemEntryBase<SystemsConfig.SubSystemEntry>.AddSystem<TSystem>(string, bool)
  fullName: Quantum.SystemsConfig.SystemEntryBase<Quantum.SystemsConfig.SubSystemEntry>.AddSystem<TSystem>(string, bool)
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of SystemsConfig.SubSystemEntry).AddSystem(Of TSystem)(String, Boolean)
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of Quantum.SystemsConfig.SubSystemEntry).AddSystem(Of TSystem)(String, Boolean)
  name.vb: AddSystem(Of TSystem)(String, Boolean)
  spec.csharp:
  - uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.AddSystem``1(System.String,System.Boolean)
    name: AddSystem
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  - name: <
  - name: TSystem
  - name: '>'
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
  spec.vb:
  - uid: Quantum.SystemsConfig.SystemEntryBase{Quantum.SystemsConfig.SubSystemEntry}.AddSystem``1(System.String,System.Boolean)
    name: AddSystem
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  - name: (
  - name: Of
  - name: " "
  - name: TSystem
  - name: )
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: Quantum.SystemsConfig.SystemEntryBase.SystemType
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.SystemType
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_SystemType
  name: SystemType
  nameWithType: SystemsConfig.SystemEntryBase.SystemType
  fullName: Quantum.SystemsConfig.SystemEntryBase.SystemType
- uid: Quantum.SystemsConfig.SystemEntryBase.SystemName
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.SystemName
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_SystemName
  name: SystemName
  nameWithType: SystemsConfig.SystemEntryBase.SystemName
  fullName: Quantum.SystemsConfig.SystemEntryBase.SystemName
- uid: Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_StartDisabled
  name: StartDisabled
  nameWithType: SystemsConfig.SystemEntryBase.StartDisabled
  fullName: Quantum.SystemsConfig.SystemEntryBase.StartDisabled
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quantum.SystemsConfig.SystemEntryBase`1
  commentId: T:Quantum.SystemsConfig.SystemEntryBase`1
  href: Quantum.SystemsConfig.html
  name: SystemsConfig.SystemEntryBase<T>
  nameWithType: SystemsConfig.SystemEntryBase<T>
  fullName: Quantum.SystemsConfig.SystemEntryBase<T>
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of T)
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of T)
  name.vb: SystemsConfig.SystemEntryBase(Of T)
  spec.csharp:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase`1
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase-1.html
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase`1
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase-1.html
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Quantum.SystemsConfig.SystemEntryBase`1.Children
  commentId: F:Quantum.SystemsConfig.SystemEntryBase`1.Children
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_Children
  name: Children
  nameWithType: SystemsConfig.SystemEntryBase<T>.Children
  fullName: Quantum.SystemsConfig.SystemEntryBase<T>.Children
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of T).Children
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of T).Children
- uid: Quantum.SystemsConfig.SystemEntryBase`1.GetChildren
  commentId: M:Quantum.SystemsConfig.SystemEntryBase`1.GetChildren
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  name: GetChildren()
  nameWithType: SystemsConfig.SystemEntryBase<T>.GetChildren()
  fullName: Quantum.SystemsConfig.SystemEntryBase<T>.GetChildren()
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of T).GetChildren()
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of T).GetChildren()
  spec.csharp:
  - uid: Quantum.SystemsConfig.SystemEntryBase`1.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  - name: (
  - name: )
  spec.vb:
  - uid: Quantum.SystemsConfig.SystemEntryBase`1.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_GetChildren
  - name: (
  - name: )
- uid: Quantum.SystemsConfig.SystemEntryBase`1.AddSystem``1(System.String,System.Boolean)
  commentId: M:Quantum.SystemsConfig.SystemEntryBase`1.AddSystem``1(System.String,System.Boolean)
  isExternal: true
  href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  name: AddSystem<TSystem>(string, bool)
  nameWithType: SystemsConfig.SystemEntryBase<T>.AddSystem<TSystem>(string, bool)
  fullName: Quantum.SystemsConfig.SystemEntryBase<T>.AddSystem<TSystem>(string, bool)
  nameWithType.vb: SystemsConfig.SystemEntryBase(Of T).AddSystem(Of TSystem)(String, Boolean)
  fullName.vb: Quantum.SystemsConfig.SystemEntryBase(Of T).AddSystem(Of TSystem)(String, Boolean)
  name.vb: AddSystem(Of TSystem)(String, Boolean)
  spec.csharp:
  - uid: Quantum.SystemsConfig.SystemEntryBase`1.AddSystem``1(System.String,System.Boolean)
    name: AddSystem
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  - name: <
  - name: TSystem
  - name: '>'
  - name: (
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
  spec.vb:
  - uid: Quantum.SystemsConfig.SystemEntryBase`1.AddSystem``1(System.String,System.Boolean)
    name: AddSystem
    href: Quantum.SystemsConfig.SystemEntryBase-1.html#Quantum_SystemsConfig_SystemEntryBase_1_AddSystem__1_System_String_System_Boolean_
  - name: (
  - name: Of
  - name: " "
  - name: TSystem
  - name: )
  - name: (
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
