### YamlMime:ManagedReference
items:
- uid: Quantum.DummyConfigCounterhit
  commentId: T:Quantum.DummyConfigCounterhit
  id: DummyConfigCounterhit
  parent: Quantum
  children:
  - Quantum.DummyConfigCounterhit.AlwaysCounterhit
  - Quantum.DummyConfigCounterhit.AlwaysPunishCounter
  - Quantum.DummyConfigCounterhit.RandomAnyCounter
  - Quantum.DummyConfigCounterhit.RandomCounterhit
  - Quantum.DummyConfigCounterhit.RandomPunishCounter
  - Quantum.DummyConfigCounterhit.Standard
  langs:
  - csharp
  - vb
  name: DummyConfigCounterhit
  nameWithType: DummyConfigCounterhit
  fullName: Quantum.DummyConfigCounterhit
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: DummyConfigCounterhit
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 79
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public enum DummyConfigCounterhit
    content.vb: Public Enum DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.Standard
  commentId: F:Quantum.DummyConfigCounterhit.Standard
  id: Standard
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: Standard
  nameWithType: DummyConfigCounterhit.Standard
  fullName: Quantum.DummyConfigCounterhit.Standard
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Standard
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 80
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Standard = 0
    return:
      type: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.AlwaysCounterhit
  commentId: F:Quantum.DummyConfigCounterhit.AlwaysCounterhit
  id: AlwaysCounterhit
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: AlwaysCounterhit
  nameWithType: DummyConfigCounterhit.AlwaysCounterhit
  fullName: Quantum.DummyConfigCounterhit.AlwaysCounterhit
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AlwaysCounterhit
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 81
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: AlwaysCounterhit = 1
    return:
      type: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.AlwaysPunishCounter
  commentId: F:Quantum.DummyConfigCounterhit.AlwaysPunishCounter
  id: AlwaysPunishCounter
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: AlwaysPunishCounter
  nameWithType: DummyConfigCounterhit.AlwaysPunishCounter
  fullName: Quantum.DummyConfigCounterhit.AlwaysPunishCounter
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AlwaysPunishCounter
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 82
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: AlwaysPunishCounter = 2
    return:
      type: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.RandomCounterhit
  commentId: F:Quantum.DummyConfigCounterhit.RandomCounterhit
  id: RandomCounterhit
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: RandomCounterhit
  nameWithType: DummyConfigCounterhit.RandomCounterhit
  fullName: Quantum.DummyConfigCounterhit.RandomCounterhit
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: RandomCounterhit
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 83
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: RandomCounterhit = 3
    return:
      type: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.RandomPunishCounter
  commentId: F:Quantum.DummyConfigCounterhit.RandomPunishCounter
  id: RandomPunishCounter
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: RandomPunishCounter
  nameWithType: DummyConfigCounterhit.RandomPunishCounter
  fullName: Quantum.DummyConfigCounterhit.RandomPunishCounter
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: RandomPunishCounter
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 84
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: RandomPunishCounter = 4
    return:
      type: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyConfigCounterhit.RandomAnyCounter
  commentId: F:Quantum.DummyConfigCounterhit.RandomAnyCounter
  id: RandomAnyCounter
  parent: Quantum.DummyConfigCounterhit
  langs:
  - csharp
  - vb
  name: RandomAnyCounter
  nameWithType: DummyConfigCounterhit.RandomAnyCounter
  fullName: Quantum.DummyConfigCounterhit.RandomAnyCounter
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: RandomAnyCounter
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 85
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: RandomAnyCounter = 5
    return:
      type: Quantum.DummyConfigCounterhit
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.DummyConfigCounterhit
  commentId: T:Quantum.DummyConfigCounterhit
  parent: Quantum
  href: Quantum.DummyConfigCounterhit.html
  name: DummyConfigCounterhit
  nameWithType: DummyConfigCounterhit
  fullName: Quantum.DummyConfigCounterhit
