### YamlMime:ManagedReference
items:
- uid: Quantum.QuantumGame.ConfigurationsContainer
  commentId: T:Quantum.QuantumGame.ConfigurationsContainer
  id: QuantumGame.ConfigurationsContainer
  parent: Quantum
  children:
  - Quantum.QuantumGame.ConfigurationsContainer.Runtime
  - Quantum.QuantumGame.ConfigurationsContainer.Simulation
  langs:
  - csharp
  - vb
  name: QuantumGame.ConfigurationsContainer
  nameWithType: QuantumGame.ConfigurationsContainer
  fullName: Quantum.QuantumGame.ConfigurationsContainer
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: ConfigurationsContainer
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
    startLine: 2823
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Stores runtime config and simulation config for this session.
  example: []
  syntax:
    content: public class QuantumGame.ConfigurationsContainer
    content.vb: Public Class QuantumGame.ConfigurationsContainer
  inheritance:
  - System.Object
- uid: Quantum.QuantumGame.ConfigurationsContainer.Runtime
  commentId: F:Quantum.QuantumGame.ConfigurationsContainer.Runtime
  id: Runtime
  parent: Quantum.QuantumGame.ConfigurationsContainer
  langs:
  - csharp
  - vb
  name: Runtime
  nameWithType: QuantumGame.ConfigurationsContainer.Runtime
  fullName: Quantum.QuantumGame.ConfigurationsContainer.Runtime
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Runtime
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
    startLine: 2827
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Runtime config finally used by the (online) simulation.
  example: []
  syntax:
    content: public RuntimeConfig Runtime
    return:
      type: Quantum.RuntimeConfig
    content.vb: Public Runtime As RuntimeConfig
- uid: Quantum.QuantumGame.ConfigurationsContainer.Simulation
  commentId: F:Quantum.QuantumGame.ConfigurationsContainer.Simulation
  id: Simulation
  parent: Quantum.QuantumGame.ConfigurationsContainer
  langs:
  - csharp
  - vb
  name: Simulation
  nameWithType: QuantumGame.ConfigurationsContainer.Simulation
  fullName: Quantum.QuantumGame.ConfigurationsContainer.Simulation
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Simulation
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/QuantumSimulationCore.cs
    startLine: 2831
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: Access to the simulation config used by the (online) simulation.
  example: []
  syntax:
    content: public SimulationConfig Simulation
    return:
      type: Quantum.SimulationConfig
    content.vb: Public Simulation As SimulationConfig
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quantum.RuntimeConfig
  commentId: T:Quantum.RuntimeConfig
  parent: Quantum
  href: Quantum.RuntimeConfig.html
  name: RuntimeConfig
  nameWithType: RuntimeConfig
  fullName: Quantum.RuntimeConfig
- uid: Quantum.SimulationConfig
  commentId: T:Quantum.SimulationConfig
  parent: Quantum
  href: Quantum.SimulationConfig.html
  name: SimulationConfig
  nameWithType: SimulationConfig
  fullName: Quantum.SimulationConfig
