### YamlMime:ManagedReference
items:
- uid: Quantum.DummyConfigBehaviour
  commentId: T:Quantum.DummyConfigBehaviour
  id: DummyConfigBehaviour
  parent: Quantum
  children:
  - Quantum.DummyConfigBehaviour.DoubleJump
  - Quantum.DummyConfigBehaviour.Jumping
  - Quantum.DummyConfigBehaviour.Standing
  langs:
  - csharp
  - vb
  name: DummyConfigBehaviour
  nameWithType: DummyConfigBehaviour
  fullName: Quantum.DummyConfigBehaviour
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: DummyConfigBehaviour
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 74
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public enum DummyConfigBehaviour
    content.vb: Public Enum DummyConfigBehaviour
- uid: Quantum.DummyConfigBehaviour.Standing
  commentId: F:Quantum.DummyConfigBehaviour.Standing
  id: Standing
  parent: Quantum.DummyConfigBehaviour
  langs:
  - csharp
  - vb
  name: Standing
  nameWithType: DummyConfigBehaviour.Standing
  fullName: Quantum.DummyConfigBehaviour.Standing
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Standing
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 75
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Standing = 0
    return:
      type: Quantum.DummyConfigBehaviour
- uid: Quantum.DummyConfigBehaviour.Jumping
  commentId: F:Quantum.DummyConfigBehaviour.Jumping
  id: Jumping
  parent: Quantum.DummyConfigBehaviour
  langs:
  - csharp
  - vb
  name: Jumping
  nameWithType: DummyConfigBehaviour.Jumping
  fullName: Quantum.DummyConfigBehaviour.Jumping
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Jumping
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 76
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Jumping = 1
    return:
      type: Quantum.DummyConfigBehaviour
- uid: Quantum.DummyConfigBehaviour.DoubleJump
  commentId: F:Quantum.DummyConfigBehaviour.DoubleJump
  id: DoubleJump
  parent: Quantum.DummyConfigBehaviour
  langs:
  - csharp
  - vb
  name: DoubleJump
  nameWithType: DummyConfigBehaviour.DoubleJump
  fullName: Quantum.DummyConfigBehaviour.DoubleJump
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: DoubleJump
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs
    startLine: 77
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: DoubleJump = 2
    return:
      type: Quantum.DummyConfigBehaviour
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.DummyConfigBehaviour
  commentId: T:Quantum.DummyConfigBehaviour
  parent: Quantum
  href: Quantum.DummyConfigBehaviour.html
  name: DummyConfigBehaviour
  nameWithType: DummyConfigBehaviour
  fullName: Quantum.DummyConfigBehaviour
