### YamlMime:ManagedReference
items:
- uid: Quantum.SystemsConfig.SubSubSystemEntry
  commentId: T:Quantum.SystemsConfig.SubSubSystemEntry
  id: SystemsConfig.SubSubSystemEntry
  parent: Quantum
  children:
  - Quantum.SystemsConfig.SubSubSystemEntry.GetChildren
  langs:
  - csharp
  - vb
  name: SystemsConfig.SubSubSystemEntry
  nameWithType: SystemsConfig.SubSubSystemEntry
  fullName: Quantum.SystemsConfig.SubSubSystemEntry
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: SubSubSystemEntry
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
    startLine: 91
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: 2nd sub level system type.
  example: []
  syntax:
    content: >-
      [Serializable]

      public class SystemsConfig.SubSubSystemEntry : SystemsConfig.SystemEntryBase
    content.vb: >-
      <Serializable>

      Public Class SystemsConfig.SubSubSystemEntry Inherits SystemsConfig.SystemEntryBase
  inheritance:
  - System.Object
  - Quantum.SystemsConfig.SystemEntryBase
  inheritedMembers:
  - Quantum.SystemsConfig.SystemEntryBase.SystemType
  - Quantum.SystemsConfig.SystemEntryBase.SystemName
  - Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  attributes:
  - type: System.SerializableAttribute
    ctor: System.SerializableAttribute.#ctor
    arguments: []
- uid: Quantum.SystemsConfig.SubSubSystemEntry.GetChildren
  commentId: M:Quantum.SystemsConfig.SubSubSystemEntry.GetChildren
  id: GetChildren
  parent: Quantum.SystemsConfig.SubSubSystemEntry
  langs:
  - csharp
  - vb
  name: GetChildren()
  nameWithType: SystemsConfig.SubSubSystemEntry.GetChildren()
  fullName: Quantum.SystemsConfig.SubSubSystemEntry.GetChildren()
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetChildren
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/Quantum/Simulation/SystemsConfig.cs
    startLine: 97
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  summary: This system cannot have children.
  example: []
  syntax:
    content: public override IReadOnlyList<SystemsConfig.SystemEntryBase> GetChildren()
    return:
      type: System.Collections.Generic.IReadOnlyList{Quantum.SystemsConfig.SystemEntryBase}
      description: Empty array
    content.vb: Public Overrides Function GetChildren() As IReadOnlyList(Of SystemsConfig.SystemEntryBase)
  overridden: Quantum.SystemsConfig.SystemEntryBase.GetChildren
  overload: Quantum.SystemsConfig.SubSubSystemEntry.GetChildren*
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Quantum.SystemsConfig.SystemEntryBase
  commentId: T:Quantum.SystemsConfig.SystemEntryBase
  parent: Quantum
  href: Quantum.SystemsConfig.html
  name: SystemsConfig.SystemEntryBase
  nameWithType: SystemsConfig.SystemEntryBase
  fullName: Quantum.SystemsConfig.SystemEntryBase
  spec.csharp:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
  spec.vb:
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
- uid: Quantum.SystemsConfig.SystemEntryBase.SystemType
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.SystemType
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_SystemType
  name: SystemType
  nameWithType: SystemsConfig.SystemEntryBase.SystemType
  fullName: Quantum.SystemsConfig.SystemEntryBase.SystemType
- uid: Quantum.SystemsConfig.SystemEntryBase.SystemName
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.SystemName
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_SystemName
  name: SystemName
  nameWithType: SystemsConfig.SystemEntryBase.SystemName
  fullName: Quantum.SystemsConfig.SystemEntryBase.SystemName
- uid: Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  commentId: F:Quantum.SystemsConfig.SystemEntryBase.StartDisabled
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_StartDisabled
  name: StartDisabled
  nameWithType: SystemsConfig.SystemEntryBase.StartDisabled
  fullName: Quantum.SystemsConfig.SystemEntryBase.StartDisabled
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quantum.SystemsConfig.SystemEntryBase.GetChildren
  commentId: M:Quantum.SystemsConfig.SystemEntryBase.GetChildren
  parent: Quantum.SystemsConfig.SystemEntryBase
  href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_GetChildren
  name: GetChildren()
  nameWithType: SystemsConfig.SystemEntryBase.GetChildren()
  fullName: Quantum.SystemsConfig.SystemEntryBase.GetChildren()
  spec.csharp:
  - uid: Quantum.SystemsConfig.SystemEntryBase.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_GetChildren
  - name: (
  - name: )
  spec.vb:
  - uid: Quantum.SystemsConfig.SystemEntryBase.GetChildren
    name: GetChildren
    href: Quantum.SystemsConfig.SystemEntryBase.html#Quantum_SystemsConfig_SystemEntryBase_GetChildren
  - name: (
  - name: )
- uid: Quantum.SystemsConfig.SubSubSystemEntry.GetChildren*
  commentId: Overload:Quantum.SystemsConfig.SubSubSystemEntry.GetChildren
  href: Quantum.SystemsConfig.SubSubSystemEntry.html#Quantum_SystemsConfig_SubSubSystemEntry_GetChildren
  name: GetChildren
  nameWithType: SystemsConfig.SubSubSystemEntry.GetChildren
  fullName: Quantum.SystemsConfig.SubSubSystemEntry.GetChildren
- uid: System.Collections.Generic.IReadOnlyList{Quantum.SystemsConfig.SystemEntryBase}
  commentId: T:System.Collections.Generic.IReadOnlyList{Quantum.SystemsConfig.SystemEntryBase}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyList`1
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<SystemsConfig.SystemEntryBase>
  nameWithType: IReadOnlyList<SystemsConfig.SystemEntryBase>
  fullName: System.Collections.Generic.IReadOnlyList<Quantum.SystemsConfig.SystemEntryBase>
  nameWithType.vb: IReadOnlyList(Of SystemsConfig.SystemEntryBase)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of Quantum.SystemsConfig.SystemEntryBase)
  name.vb: IReadOnlyList(Of SystemsConfig.SystemEntryBase)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - uid: Quantum.SystemsConfig
    name: SystemsConfig
    href: Quantum.SystemsConfig.html
  - name: .
  - uid: Quantum.SystemsConfig.SystemEntryBase
    name: SystemEntryBase
    href: Quantum.SystemsConfig.SystemEntryBase.html
  - name: )
- uid: System.Collections.Generic.IReadOnlyList`1
  commentId: T:System.Collections.Generic.IReadOnlyList`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  name: IReadOnlyList<T>
  nameWithType: IReadOnlyList<T>
  fullName: System.Collections.Generic.IReadOnlyList<T>
  nameWithType.vb: IReadOnlyList(Of T)
  fullName.vb: System.Collections.Generic.IReadOnlyList(Of T)
  name.vb: IReadOnlyList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyList`1
    name: IReadOnlyList
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlylist-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
