### YamlMime:ManagedReference
items:
- uid: Quantum.HNSFConfig.EValueType
  commentId: T:Quantum.HNSFConfig.EValueType
  id: HNSFConfig.EValueType
  parent: Quantum
  children:
  - Quantum.HNSFConfig.EValueType.AssetRef
  - Quantum.HNSFConfig.EValueType.Bool
  - Quantum.HNSFConfig.EValueType.Byte
  - Quantum.HNSFConfig.EValueType.EntityRef
  - Quantum.HNSFConfig.EValueType.FP
  - Quantum.HNSFConfig.EValueType.FPVector2
  - Quantum.HNSFConfig.EValueType.FPVector3
  - Quantum.HNSFConfig.EValueType.Int
  - Quantum.HNSFConfig.EValueType.None
  - Quantum.HNSFConfig.EValueType.String
  langs:
  - csharp
  - vb
  name: HNSFConfig.EValueType
  nameWithType: HNSFConfig.EValueType
  fullName: Quantum.HNSFConfig.EValueType
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: EValueType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 8
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public enum HNSFConfig.EValueType
    content.vb: Public Enum HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.None
  commentId: F:Quantum.HNSFConfig.EValueType.None
  id: None
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: None
  nameWithType: HNSFConfig.EValueType.None
  fullName: Quantum.HNSFConfig.EValueType.None
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: None
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 10
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: None = 0
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.Int
  commentId: F:Quantum.HNSFConfig.EValueType.Int
  id: Int
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: Int
  nameWithType: HNSFConfig.EValueType.Int
  fullName: Quantum.HNSFConfig.EValueType.Int
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Int
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 11
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Int = 1
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.Bool
  commentId: F:Quantum.HNSFConfig.EValueType.Bool
  id: Bool
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: Bool
  nameWithType: HNSFConfig.EValueType.Bool
  fullName: Quantum.HNSFConfig.EValueType.Bool
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Bool
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 12
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Bool = 2
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.Byte
  commentId: F:Quantum.HNSFConfig.EValueType.Byte
  id: Byte
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: Byte
  nameWithType: HNSFConfig.EValueType.Byte
  fullName: Quantum.HNSFConfig.EValueType.Byte
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Byte
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 13
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: Byte = 3
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.FP
  commentId: F:Quantum.HNSFConfig.EValueType.FP
  id: FP
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: FP
  nameWithType: HNSFConfig.EValueType.FP
  fullName: Quantum.HNSFConfig.EValueType.FP
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FP
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 14
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: FP = 4
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.FPVector2
  commentId: F:Quantum.HNSFConfig.EValueType.FPVector2
  id: FPVector2
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: FPVector2
  nameWithType: HNSFConfig.EValueType.FPVector2
  fullName: Quantum.HNSFConfig.EValueType.FPVector2
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FPVector2
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 15
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: FPVector2 = 5
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.FPVector3
  commentId: F:Quantum.HNSFConfig.EValueType.FPVector3
  id: FPVector3
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: FPVector3
  nameWithType: HNSFConfig.EValueType.FPVector3
  fullName: Quantum.HNSFConfig.EValueType.FPVector3
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: FPVector3
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 16
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: FPVector3 = 6
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.String
  commentId: F:Quantum.HNSFConfig.EValueType.String
  id: String
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: String
  nameWithType: HNSFConfig.EValueType.String
  fullName: Quantum.HNSFConfig.EValueType.String
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: String
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 17
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: String = 7
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.EntityRef
  commentId: F:Quantum.HNSFConfig.EValueType.EntityRef
  id: EntityRef
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: EntityRef
  nameWithType: HNSFConfig.EValueType.EntityRef
  fullName: Quantum.HNSFConfig.EValueType.EntityRef
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: EntityRef
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 18
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: EntityRef = 8
    return:
      type: Quantum.HNSFConfig.EValueType
- uid: Quantum.HNSFConfig.EValueType.AssetRef
  commentId: F:Quantum.HNSFConfig.EValueType.AssetRef
  id: AssetRef
  parent: Quantum.HNSFConfig.EValueType
  langs:
  - csharp
  - vb
  name: AssetRef
  nameWithType: HNSFConfig.EValueType.AssetRef
  fullName: Quantum.HNSFConfig.EValueType.AssetRef
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AssetRef
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/HnsFramework/HNSFConfig.cs
    startLine: 19
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: AssetRef = 9
    return:
      type: Quantum.HNSFConfig.EValueType
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.HNSFConfig.EValueType
  commentId: T:Quantum.HNSFConfig.EValueType
  parent: Quantum
  href: Quantum.HNSFConfig.html
  name: HNSFConfig.EValueType
  nameWithType: HNSFConfig.EValueType
  fullName: Quantum.HNSFConfig.EValueType
  spec.csharp:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.EValueType
    name: EValueType
    href: Quantum.HNSFConfig.EValueType.html
  spec.vb:
  - uid: Quantum.HNSFConfig
    name: HNSFConfig
    href: Quantum.HNSFConfig.html
  - name: .
  - uid: Quantum.HNSFConfig.EValueType
    name: EValueType
    href: Quantum.HNSFConfig.EValueType.html
