### YamlMime:ManagedReference
items:
- uid: Quantum.AIConfigExtensions
  commentId: T:Quantum.AIConfigExtensions
  id: AIConfigExtensions
  parent: Quantum
  children:
  - Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.Core.FrameBase)
  - Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.FrameThreadSafe)
  - Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.Core.FrameBase)
  - Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.FrameThreadSafe)
  - Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.Core.FrameBase)
  - Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.FrameThreadSafe)
  langs:
  - csharp
  - vb
  name: AIConfigExtensions
  nameWithType: AIConfigExtensions
  fullName: Quantum.AIConfigExtensions
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: AIConfigExtensions
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 8
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static class AIConfigExtensions
    content.vb: Public Module AIConfigExtensions
  inheritance:
  - System.Object
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.Core.FrameBase)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.Core.FrameBase)
  id: GetConfig(Quantum.HFSMAgent,Quantum.Core.FrameBase)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(HFSMAgent, FrameBase)
  nameWithType: AIConfigExtensions.GetConfig(HFSMAgent, FrameBase)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent, Quantum.Core.FrameBase)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 10
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this HFSMAgent agent, FrameBase frame)
    parameters:
    - id: agent
      type: Quantum.HFSMAgent
    - id: frame
      type: Quantum.Core.FrameBase
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As HFSMAgent, frame As FrameBase) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.FrameThreadSafe)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent,Quantum.FrameThreadSafe)
  id: GetConfig(Quantum.HFSMAgent,Quantum.FrameThreadSafe)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(HFSMAgent, FrameThreadSafe)
  nameWithType: AIConfigExtensions.GetConfig(HFSMAgent, FrameThreadSafe)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.HFSMAgent, Quantum.FrameThreadSafe)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 14
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this HFSMAgent agent, FrameThreadSafe frame)
    parameters:
    - id: agent
      type: Quantum.HFSMAgent
    - id: frame
      type: Quantum.FrameThreadSafe
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As HFSMAgent, frame As FrameThreadSafe) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.Core.FrameBase)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.Core.FrameBase)
  id: GetConfig(Quantum.BTAgent,Quantum.Core.FrameBase)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(BTAgent, FrameBase)
  nameWithType: AIConfigExtensions.GetConfig(BTAgent, FrameBase)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent, Quantum.Core.FrameBase)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 19
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this BTAgent agent, FrameBase frame)
    parameters:
    - id: agent
      type: Quantum.BTAgent
    - id: frame
      type: Quantum.Core.FrameBase
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As BTAgent, frame As FrameBase) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.FrameThreadSafe)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent,Quantum.FrameThreadSafe)
  id: GetConfig(Quantum.BTAgent,Quantum.FrameThreadSafe)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(BTAgent, FrameThreadSafe)
  nameWithType: AIConfigExtensions.GetConfig(BTAgent, FrameThreadSafe)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.BTAgent, Quantum.FrameThreadSafe)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 24
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this BTAgent agent, FrameThreadSafe frame)
    parameters:
    - id: agent
      type: Quantum.BTAgent
    - id: frame
      type: Quantum.FrameThreadSafe
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As BTAgent, frame As FrameThreadSafe) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.Core.FrameBase)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.Core.FrameBase)
  id: GetConfig(Quantum.UTAgent,Quantum.Core.FrameBase)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(UTAgent, FrameBase)
  nameWithType: AIConfigExtensions.GetConfig(UTAgent, FrameBase)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent, Quantum.Core.FrameBase)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 29
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this UTAgent agent, FrameBase frame)
    parameters:
    - id: agent
      type: Quantum.UTAgent
    - id: frame
      type: Quantum.Core.FrameBase
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As UTAgent, frame As FrameBase) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
- uid: Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.FrameThreadSafe)
  commentId: M:Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent,Quantum.FrameThreadSafe)
  id: GetConfig(Quantum.UTAgent,Quantum.FrameThreadSafe)
  isExtensionMethod: true
  parent: Quantum.AIConfigExtensions
  langs:
  - csharp
  - vb
  name: GetConfig(UTAgent, FrameThreadSafe)
  nameWithType: AIConfigExtensions.GetConfig(UTAgent, FrameThreadSafe)
  fullName: Quantum.AIConfigExtensions.GetConfig(Quantum.UTAgent, Quantum.FrameThreadSafe)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GetConfig
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/Photon/QuantumAddons/QuantumBotSDK/Simulation/Core/AIConfig.cs
    startLine: 34
  assemblies:
  - Quantum.Simulation
  namespace: Quantum
  syntax:
    content: public static AIConfig GetConfig(this UTAgent agent, FrameThreadSafe frame)
    parameters:
    - id: agent
      type: Quantum.UTAgent
    - id: frame
      type: Quantum.FrameThreadSafe
    return:
      type: Quantum.AIConfig
    content.vb: Public Shared Function GetConfig(agent As UTAgent, frame As FrameThreadSafe) As AIConfig
  overload: Quantum.AIConfigExtensions.GetConfig*
references:
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quantum.AIConfigExtensions.GetConfig*
  commentId: Overload:Quantum.AIConfigExtensions.GetConfig
  href: Quantum.AIConfigExtensions.html#Quantum_AIConfigExtensions_GetConfig_Quantum_HFSMAgent_Quantum_Core_FrameBase_
  name: GetConfig
  nameWithType: AIConfigExtensions.GetConfig
  fullName: Quantum.AIConfigExtensions.GetConfig
- uid: Quantum.HFSMAgent
  commentId: T:Quantum.HFSMAgent
  parent: Quantum
  isExternal: true
  name: HFSMAgent
  nameWithType: HFSMAgent
  fullName: Quantum.HFSMAgent
- uid: Quantum.Core.FrameBase
  commentId: T:Quantum.Core.FrameBase
  parent: Quantum.Core
  isExternal: true
  name: FrameBase
  nameWithType: FrameBase
  fullName: Quantum.Core.FrameBase
- uid: Quantum.AIConfig
  commentId: T:Quantum.AIConfig
  parent: Quantum
  href: Quantum.AIConfig.html
  name: AIConfig
  nameWithType: AIConfig
  fullName: Quantum.AIConfig
- uid: Quantum.Core
  commentId: N:Quantum.Core
  href: Quantum.html
  name: Quantum.Core
  nameWithType: Quantum.Core
  fullName: Quantum.Core
  spec.csharp:
  - uid: Quantum
    name: Quantum
    href: Quantum.html
  - name: .
  - uid: Quantum.Core
    name: Core
    href: Quantum.Core.html
  spec.vb:
  - uid: Quantum
    name: Quantum
    href: Quantum.html
  - name: .
  - uid: Quantum.Core
    name: Core
    href: Quantum.Core.html
- uid: Quantum.FrameThreadSafe
  commentId: T:Quantum.FrameThreadSafe
  parent: Quantum
  isExternal: true
  name: FrameThreadSafe
  nameWithType: FrameThreadSafe
  fullName: Quantum.FrameThreadSafe
- uid: Quantum.BTAgent
  commentId: T:Quantum.BTAgent
  parent: Quantum
  isExternal: true
  name: BTAgent
  nameWithType: BTAgent
  fullName: Quantum.BTAgent
- uid: Quantum.UTAgent
  commentId: T:Quantum.UTAgent
  parent: Quantum
  isExternal: true
  name: UTAgent
  nameWithType: UTAgent
  fullName: Quantum.UTAgent
