### YamlMime:ManagedReference
items:
- uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  commentId: T:rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  id: PauseMenuDummySettingsHandler.MenuTypes
  parent: rwby.core.gamemodes.training.ui
  children:
  - rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Fighter
  - rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Main
  langs:
  - csharp
  - vb
  name: PauseMenuDummySettingsHandler.MenuTypes
  nameWithType: PauseMenuDummySettingsHandler.MenuTypes
  fullName: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: MenuTypes
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
    startLine: 7
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public enum PauseMenuDummySettingsHandler.MenuTypes
    content.vb: Public Enum PauseMenuDummySettingsHandler.MenuTypes
- uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Main
  commentId: F:rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Main
  id: Main
  parent: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  langs:
  - csharp
  - vb
  name: Main
  nameWithType: PauseMenuDummySettingsHandler.MenuTypes.Main
  fullName: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Main
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Main
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
    startLine: 9
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: Main = 0
    return:
      type: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
- uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Fighter
  commentId: F:rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Fighter
  id: Fighter
  parent: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  langs:
  - csharp
  - vb
  name: Fighter
  nameWithType: PauseMenuDummySettingsHandler.MenuTypes.Fighter
  fullName: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.Fighter
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Fighter
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuDummySettingsHandler.cs
    startLine: 10
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: Fighter = 1
    return:
      type: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
references:
- uid: rwby.core.gamemodes.training.ui
  commentId: N:rwby.core.gamemodes.training.ui
  href: rwby.html
  name: rwby.core.gamemodes.training.ui
  nameWithType: rwby.core.gamemodes.training.ui
  fullName: rwby.core.gamemodes.training.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
- uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  commentId: T:rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  parent: rwby.core.gamemodes.training.ui
  href: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.html
  name: PauseMenuDummySettingsHandler.MenuTypes
  nameWithType: PauseMenuDummySettingsHandler.MenuTypes
  fullName: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
  spec.csharp:
  - uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler
    name: PauseMenuDummySettingsHandler
    href: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
    name: MenuTypes
    href: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.html
  spec.vb:
  - uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler
    name: PauseMenuDummySettingsHandler
    href: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes
    name: MenuTypes
    href: rwby.core.gamemodes.training.ui.PauseMenuDummySettingsHandler.MenuTypes.html
