### YamlMime:ManagedReference
items:
- uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  commentId: T:rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  id: PauseMenuHandlerBasicSettingsMenu.MenuType
  parent: rwby.core.gamemodes.training.ui
  children:
  - rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.commandList
  - rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.main
  langs:
  - csharp
  - vb
  name: PauseMenuHandlerBasicSettingsMenu.MenuType
  nameWithType: PauseMenuHandlerBasicSettingsMenu.MenuType
  fullName: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  type: Enum
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: MenuType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
    startLine: 8
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public enum PauseMenuHandlerBasicSettingsMenu.MenuType
    content.vb: Public Enum PauseMenuHandlerBasicSettingsMenu.MenuType
- uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.main
  commentId: F:rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.main
  id: main
  parent: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  langs:
  - csharp
  - vb
  name: main
  nameWithType: PauseMenuHandlerBasicSettingsMenu.MenuType.main
  fullName: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.main
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: main
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
    startLine: 10
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: main = 0
    return:
      type: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
- uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.commandList
  commentId: F:rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.commandList
  id: commandList
  parent: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  langs:
  - csharp
  - vb
  name: commandList
  nameWithType: PauseMenuHandlerBasicSettingsMenu.MenuType.commandList
  fullName: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.commandList
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: commandList
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/PauseMenuHandlerBasicSettingsMenu.cs
    startLine: 11
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: commandList = 1
    return:
      type: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
references:
- uid: rwby.core.gamemodes.training.ui
  commentId: N:rwby.core.gamemodes.training.ui
  href: rwby.html
  name: rwby.core.gamemodes.training.ui
  nameWithType: rwby.core.gamemodes.training.ui
  fullName: rwby.core.gamemodes.training.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
- uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  commentId: T:rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  parent: rwby.core.gamemodes.training.ui
  href: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.html
  name: PauseMenuHandlerBasicSettingsMenu.MenuType
  nameWithType: PauseMenuHandlerBasicSettingsMenu.MenuType
  fullName: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
  spec.csharp:
  - uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu
    name: PauseMenuHandlerBasicSettingsMenu
    href: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
    name: MenuType
    href: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.html
  spec.vb:
  - uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu
    name: PauseMenuHandlerBasicSettingsMenu
    href: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType
    name: MenuType
    href: rwby.core.gamemodes.training.ui.PauseMenuHandlerBasicSettingsMenu.MenuType.html
