### YamlMime:ManagedReference
items:
- uid: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler
  commentId: T:rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler
  id: GamemodeTrainingSettingsUIHandler
  parent: rwby.core.gamemodes.training.ui
  children:
  - rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  - rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  langs:
  - csharp
  - vb
  name: GamemodeTrainingSettingsUIHandler
  nameWithType: GamemodeTrainingSettingsUIHandler
  fullName: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: GamemodeTrainingSettingsUIHandler
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
    startLine: 5
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: 'public class GamemodeTrainingSettingsUIHandler : MonoBehaviour'
    content.vb: Public Class GamemodeTrainingSettingsUIHandler Inherits MonoBehaviour
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.Component
  - UnityEngine.Behaviour
  - UnityEngine.MonoBehaviour
- uid: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  commentId: M:rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  id: UI_FillGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  parent: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler
  langs:
  - csharp
  - vb
  name: UI_FillGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen, GamemodeSettingsBase)
  nameWithType: GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen, GamemodeSettingsBase)
  fullName: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen, Quantum.GamemodeSettingsBase)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: UI_FillGamemodeSettings
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
    startLine: 7
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public void UI_FillGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen settingsScreen, GamemodeSettingsBase gamemodeSettings)
    parameters:
    - id: settingsScreen
      type: rwby.VytalMatchSceneGamemodeSettingsScreen
    - id: gamemodeSettings
      type: Quantum.GamemodeSettingsBase
    content.vb: Public Sub UI_FillGamemodeSettings(settingsScreen As VytalMatchSceneGamemodeSettingsScreen, gamemodeSettings As GamemodeSettingsBase)
  overload: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings*
- uid: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  commentId: M:rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  id: ApplyGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen,Quantum.GamemodeSettingsBase)
  parent: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler
  langs:
  - csharp
  - vb
  name: ApplyGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen, GamemodeSettingsBase)
  nameWithType: GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen, GamemodeSettingsBase)
  fullName: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings(rwby.VytalMatchSceneGamemodeSettingsScreen, Quantum.GamemodeSettingsBase)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: ApplyGamemodeSettings
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/View/GamemodeTrainingSettingsUIHandler.cs
    startLine: 14
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public void ApplyGamemodeSettings(VytalMatchSceneGamemodeSettingsScreen settingsScreen, GamemodeSettingsBase gamemodeSettings)
    parameters:
    - id: settingsScreen
      type: rwby.VytalMatchSceneGamemodeSettingsScreen
    - id: gamemodeSettings
      type: Quantum.GamemodeSettingsBase
    content.vb: Public Sub ApplyGamemodeSettings(settingsScreen As VytalMatchSceneGamemodeSettingsScreen, gamemodeSettings As GamemodeSettingsBase)
  overload: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings*
references:
- uid: rwby.core.gamemodes.training.ui
  commentId: N:rwby.core.gamemodes.training.ui
  href: rwby.html
  name: rwby.core.gamemodes.training.ui
  nameWithType: rwby.core.gamemodes.training.ui
  fullName: rwby.core.gamemodes.training.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.Component
  commentId: T:UnityEngine.Component
  parent: UnityEngine
  isExternal: true
  name: Component
  nameWithType: Component
  fullName: UnityEngine.Component
- uid: UnityEngine.Behaviour
  commentId: T:UnityEngine.Behaviour
  parent: UnityEngine
  isExternal: true
  name: Behaviour
  nameWithType: Behaviour
  fullName: UnityEngine.Behaviour
- uid: UnityEngine.MonoBehaviour
  commentId: T:UnityEngine.MonoBehaviour
  parent: UnityEngine
  isExternal: true
  name: MonoBehaviour
  nameWithType: MonoBehaviour
  fullName: UnityEngine.MonoBehaviour
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings*
  commentId: Overload:rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings
  href: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.html#rwby_core_gamemodes_training_ui_GamemodeTrainingSettingsUIHandler_UI_FillGamemodeSettings_rwby_VytalMatchSceneGamemodeSettingsScreen_Quantum_GamemodeSettingsBase_
  name: UI_FillGamemodeSettings
  nameWithType: GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings
  fullName: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.UI_FillGamemodeSettings
- uid: rwby.VytalMatchSceneGamemodeSettingsScreen
  commentId: T:rwby.VytalMatchSceneGamemodeSettingsScreen
  parent: rwby
  href: rwby.VytalMatchSceneGamemodeSettingsScreen.html
  name: VytalMatchSceneGamemodeSettingsScreen
  nameWithType: VytalMatchSceneGamemodeSettingsScreen
  fullName: rwby.VytalMatchSceneGamemodeSettingsScreen
- uid: Quantum.GamemodeSettingsBase
  commentId: T:Quantum.GamemodeSettingsBase
  parent: Quantum
  href: Quantum.GamemodeSettingsBase.html
  name: GamemodeSettingsBase
  nameWithType: GamemodeSettingsBase
  fullName: Quantum.GamemodeSettingsBase
- uid: rwby
  commentId: N:rwby
  href: rwby.html
  name: rwby
  nameWithType: rwby
  fullName: rwby
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings*
  commentId: Overload:rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings
  href: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.html#rwby_core_gamemodes_training_ui_GamemodeTrainingSettingsUIHandler_ApplyGamemodeSettings_rwby_VytalMatchSceneGamemodeSettingsScreen_Quantum_GamemodeSettingsBase_
  name: ApplyGamemodeSettings
  nameWithType: GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings
  fullName: rwby.core.gamemodes.training.ui.GamemodeTrainingSettingsUIHandler.ApplyGamemodeSettings
