### YamlMime:ManagedReference
items:
- uid: rwby.core.gamemodes.training.ui.DummySettingsFighterSelectScreen.OnFighterSelected
  commentId: T:rwby.core.gamemodes.training.ui.DummySettingsFighterSelectScreen.OnFighterSelected
  id: DummySettingsFighterSelectScreen.OnFighterSelected
  parent: rwby.core.gamemodes.training.ui
  children: []
  langs:
  - csharp
  - vb
  name: DummySettingsFighterSelectScreen.OnFighterSelected
  nameWithType: DummySettingsFighterSelectScreen.OnFighterSelected
  fullName: rwby.core.gamemodes.training.ui.DummySettingsFighterSelectScreen.OnFighterSelected
  type: Delegate
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsFighterSelectScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: OnFighterSelected
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsFighterSelectScreen.cs
    startLine: 14
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public delegate void DummySettingsFighterSelectScreen.OnFighterSelected(IFighterDefinition fighter)
    parameters:
    - id: fighter
      type: Global.IFighterDefinition
    content.vb: Public Delegate Sub DummySettingsFighterSelectScreen.OnFighterSelected(fighter As IFighterDefinition)
references:
- uid: rwby.core.gamemodes.training.ui
  commentId: N:rwby.core.gamemodes.training.ui
  href: rwby.html
  name: rwby.core.gamemodes.training.ui
  nameWithType: rwby.core.gamemodes.training.ui
  fullName: rwby.core.gamemodes.training.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
- uid: Global.IFighterDefinition
  commentId: T:Global.IFighterDefinition
  href: IFighterDefinition.html
  name: IFighterDefinition
  nameWithType: IFighterDefinition
  fullName: IFighterDefinition
