### YamlMime:ManagedReference
items:
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  commentId: T:rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  id: DummySettingsMainScreen
  parent: rwby.core.gamemodes.training.ui
  children:
  - rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  - rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose(rwby.ui.MenuDirection,System.Boolean)
  - rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionPrefab
  - rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionScrollRect
  - rwby.core.gamemodes.training.ui.DummySettingsMainScreen.pauseMenuHandler
  langs:
  - csharp
  - vb
  name: DummySettingsMainScreen
  nameWithType: DummySettingsMainScreen
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: DummySettingsMainScreen
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 8
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: 'public class DummySettingsMainScreen : MenuBase, IMenu'
    content.vb: Public Class DummySettingsMainScreen Inherits MenuBase Implements IMenu
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.Component
  - UnityEngine.Behaviour
  - UnityEngine.MonoBehaviour
  - rwby.ui.MenuBase
  implements:
  - rwby.ui.IMenu
  inheritedMembers:
  - rwby.ui.MenuBase.MenuHandler
  - rwby.ui.MenuBase.history
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.pauseMenuHandler
  commentId: F:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.pauseMenuHandler
  id: pauseMenuHandler
  parent: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  langs:
  - csharp
  - vb
  name: pauseMenuHandler
  nameWithType: DummySettingsMainScreen.pauseMenuHandler
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.pauseMenuHandler
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: pauseMenuHandler
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 10
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public TrainingPauseMenuHandler pauseMenuHandler
    return:
      type: rwby.core.gamemodes.training.ui.TrainingPauseMenuHandler
    content.vb: Public pauseMenuHandler As TrainingPauseMenuHandler
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionPrefab
  commentId: F:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionPrefab
  id: dummySectionPrefab
  parent: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  langs:
  - csharp
  - vb
  name: dummySectionPrefab
  nameWithType: DummySettingsMainScreen.dummySectionPrefab
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionPrefab
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: dummySectionPrefab
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 11
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public DummySection dummySectionPrefab
    return:
      type: rwby.core.gamemodes.training.ui.DummySection
    content.vb: Public dummySectionPrefab As DummySection
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionScrollRect
  commentId: F:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionScrollRect
  id: dummySectionScrollRect
  parent: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  langs:
  - csharp
  - vb
  name: dummySectionScrollRect
  nameWithType: DummySettingsMainScreen.dummySectionScrollRect
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.dummySectionScrollRect
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: dummySectionScrollRect
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 12
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  syntax:
    content: public ScrollRect dummySectionScrollRect
    return:
      type: UnityEngine.UI.ScrollRect
    content.vb: Public dummySectionScrollRect As ScrollRect
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  commentId: M:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  id: Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  parent: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  langs:
  - csharp
  - vb
  name: Open(MenuDirection, IMenuHandler)
  nameWithType: DummySettingsMainScreen.Open(MenuDirection, IMenuHandler)
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open(rwby.ui.MenuDirection, rwby.ui.IMenuHandler)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Open
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 14
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  example: []
  syntax:
    content: public override void Open(MenuDirection direction, IMenuHandler menuHandler)
    parameters:
    - id: direction
      type: rwby.ui.MenuDirection
    - id: menuHandler
      type: rwby.ui.IMenuHandler
    content.vb: Public Overrides Sub Open(direction As MenuDirection, menuHandler As IMenuHandler)
  overridden: rwby.ui.MenuBase.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  overload: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open*
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose(rwby.ui.MenuDirection,System.Boolean)
  commentId: M:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose(rwby.ui.MenuDirection,System.Boolean)
  id: TryClose(rwby.ui.MenuDirection,System.Boolean)
  parent: rwby.core.gamemodes.training.ui.DummySettingsMainScreen
  langs:
  - csharp
  - vb
  name: TryClose(MenuDirection, bool)
  nameWithType: DummySettingsMainScreen.TryClose(MenuDirection, bool)
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose(rwby.ui.MenuDirection, bool)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: TryClose
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/2.Content/Gamemodes/Training/UI/DummySettingsMainScreen.cs
    startLine: 22
  assemblies:
  - Assembly-CSharp
  namespace: rwby.core.gamemodes.training.ui
  example: []
  syntax:
    content: public override bool TryClose(MenuDirection direction, bool forceClose = false)
    parameters:
    - id: direction
      type: rwby.ui.MenuDirection
    - id: forceClose
      type: System.Boolean
    return:
      type: System.Boolean
    content.vb: Public Overrides Function TryClose(direction As MenuDirection, forceClose As Boolean = False) As Boolean
  overridden: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection,System.Boolean)
  overload: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose*
  nameWithType.vb: DummySettingsMainScreen.TryClose(MenuDirection, Boolean)
  fullName.vb: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose(rwby.ui.MenuDirection, Boolean)
  name.vb: TryClose(MenuDirection, Boolean)
references:
- uid: rwby.core.gamemodes.training.ui
  commentId: N:rwby.core.gamemodes.training.ui
  href: rwby.html
  name: rwby.core.gamemodes.training.ui
  nameWithType: rwby.core.gamemodes.training.ui
  fullName: rwby.core.gamemodes.training.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  - name: .
  - uid: rwby.core.gamemodes
    name: gamemodes
    href: rwby.core.gamemodes.html
  - name: .
  - uid: rwby.core.gamemodes.training
    name: training
    href: rwby.core.gamemodes.training.html
  - name: .
  - uid: rwby.core.gamemodes.training.ui
    name: ui
    href: rwby.core.gamemodes.training.ui.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.Component
  commentId: T:UnityEngine.Component
  parent: UnityEngine
  isExternal: true
  name: Component
  nameWithType: Component
  fullName: UnityEngine.Component
- uid: UnityEngine.Behaviour
  commentId: T:UnityEngine.Behaviour
  parent: UnityEngine
  isExternal: true
  name: Behaviour
  nameWithType: Behaviour
  fullName: UnityEngine.Behaviour
- uid: UnityEngine.MonoBehaviour
  commentId: T:UnityEngine.MonoBehaviour
  parent: UnityEngine
  isExternal: true
  name: MonoBehaviour
  nameWithType: MonoBehaviour
  fullName: UnityEngine.MonoBehaviour
- uid: rwby.ui.MenuBase
  commentId: T:rwby.ui.MenuBase
  parent: rwby.ui
  href: rwby.ui.MenuBase.html
  name: MenuBase
  nameWithType: MenuBase
  fullName: rwby.ui.MenuBase
- uid: rwby.ui.IMenu
  commentId: T:rwby.ui.IMenu
  parent: rwby.ui
  href: rwby.ui.IMenu.html
  name: IMenu
  nameWithType: IMenu
  fullName: rwby.ui.IMenu
- uid: rwby.ui.MenuBase.MenuHandler
  commentId: P:rwby.ui.MenuBase.MenuHandler
  parent: rwby.ui.MenuBase
  href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_MenuHandler
  name: MenuHandler
  nameWithType: MenuBase.MenuHandler
  fullName: rwby.ui.MenuBase.MenuHandler
- uid: rwby.ui.MenuBase.history
  commentId: F:rwby.ui.MenuBase.history
  parent: rwby.ui.MenuBase
  href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_history
  name: history
  nameWithType: MenuBase.history
  fullName: rwby.ui.MenuBase.history
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: rwby.ui
  commentId: N:rwby.ui
  href: rwby.html
  name: rwby.ui
  nameWithType: rwby.ui
  fullName: rwby.ui
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.ui
    name: ui
    href: rwby.ui.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.ui
    name: ui
    href: rwby.ui.html
- uid: rwby.core.gamemodes.training.ui.TrainingPauseMenuHandler
  commentId: T:rwby.core.gamemodes.training.ui.TrainingPauseMenuHandler
  parent: rwby.core.gamemodes.training.ui
  href: rwby.core.gamemodes.training.ui.TrainingPauseMenuHandler.html
  name: TrainingPauseMenuHandler
  nameWithType: TrainingPauseMenuHandler
  fullName: rwby.core.gamemodes.training.ui.TrainingPauseMenuHandler
- uid: rwby.core.gamemodes.training.ui.DummySection
  commentId: T:rwby.core.gamemodes.training.ui.DummySection
  parent: rwby.core.gamemodes.training.ui
  href: rwby.core.gamemodes.training.ui.DummySection.html
  name: DummySection
  nameWithType: DummySection
  fullName: rwby.core.gamemodes.training.ui.DummySection
- uid: UnityEngine.UI.ScrollRect
  commentId: T:UnityEngine.UI.ScrollRect
  parent: UnityEngine.UI
  isExternal: true
  name: ScrollRect
  nameWithType: ScrollRect
  fullName: UnityEngine.UI.ScrollRect
- uid: UnityEngine.UI
  commentId: N:UnityEngine.UI
  isExternal: true
  name: UnityEngine.UI
  nameWithType: UnityEngine.UI
  fullName: UnityEngine.UI
  spec.csharp:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UI
    name: UI
    isExternal: true
  spec.vb:
  - uid: UnityEngine
    name: UnityEngine
    isExternal: true
  - name: .
  - uid: UnityEngine.UI
    name: UI
    isExternal: true
- uid: rwby.ui.MenuBase.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  commentId: M:rwby.ui.MenuBase.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
  parent: rwby.ui.MenuBase
  href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_Open_rwby_ui_MenuDirection_rwby_ui_IMenuHandler_
  name: Open(MenuDirection, IMenuHandler)
  nameWithType: MenuBase.Open(MenuDirection, IMenuHandler)
  fullName: rwby.ui.MenuBase.Open(rwby.ui.MenuDirection, rwby.ui.IMenuHandler)
  spec.csharp:
  - uid: rwby.ui.MenuBase.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
    name: Open
    href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_Open_rwby_ui_MenuDirection_rwby_ui_IMenuHandler_
  - name: (
  - uid: rwby.ui.MenuDirection
    name: MenuDirection
    href: rwby.ui.MenuDirection.html
  - name: ','
  - name: " "
  - uid: rwby.ui.IMenuHandler
    name: IMenuHandler
    href: rwby.ui.IMenuHandler.html
  - name: )
  spec.vb:
  - uid: rwby.ui.MenuBase.Open(rwby.ui.MenuDirection,rwby.ui.IMenuHandler)
    name: Open
    href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_Open_rwby_ui_MenuDirection_rwby_ui_IMenuHandler_
  - name: (
  - uid: rwby.ui.MenuDirection
    name: MenuDirection
    href: rwby.ui.MenuDirection.html
  - name: ','
  - name: " "
  - uid: rwby.ui.IMenuHandler
    name: IMenuHandler
    href: rwby.ui.IMenuHandler.html
  - name: )
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open*
  commentId: Overload:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open
  href: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.html#rwby_core_gamemodes_training_ui_DummySettingsMainScreen_Open_rwby_ui_MenuDirection_rwby_ui_IMenuHandler_
  name: Open
  nameWithType: DummySettingsMainScreen.Open
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.Open
- uid: rwby.ui.MenuDirection
  commentId: T:rwby.ui.MenuDirection
  parent: rwby.ui
  href: rwby.ui.MenuDirection.html
  name: MenuDirection
  nameWithType: MenuDirection
  fullName: rwby.ui.MenuDirection
- uid: rwby.ui.IMenuHandler
  commentId: T:rwby.ui.IMenuHandler
  parent: rwby.ui
  href: rwby.ui.IMenuHandler.html
  name: IMenuHandler
  nameWithType: IMenuHandler
  fullName: rwby.ui.IMenuHandler
- uid: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection,System.Boolean)
  commentId: M:rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection,System.Boolean)
  parent: rwby.ui.MenuBase
  isExternal: true
  href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_TryClose_rwby_ui_MenuDirection_System_Boolean_
  name: TryClose(MenuDirection, bool)
  nameWithType: MenuBase.TryClose(MenuDirection, bool)
  fullName: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection, bool)
  nameWithType.vb: MenuBase.TryClose(MenuDirection, Boolean)
  fullName.vb: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection, Boolean)
  name.vb: TryClose(MenuDirection, Boolean)
  spec.csharp:
  - uid: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection,System.Boolean)
    name: TryClose
    href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_TryClose_rwby_ui_MenuDirection_System_Boolean_
  - name: (
  - uid: rwby.ui.MenuDirection
    name: MenuDirection
    href: rwby.ui.MenuDirection.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
  spec.vb:
  - uid: rwby.ui.MenuBase.TryClose(rwby.ui.MenuDirection,System.Boolean)
    name: TryClose
    href: rwby.ui.MenuBase.html#rwby_ui_MenuBase_TryClose_rwby_ui_MenuDirection_System_Boolean_
  - name: (
  - uid: rwby.ui.MenuDirection
    name: MenuDirection
    href: rwby.ui.MenuDirection.html
  - name: ','
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
- uid: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose*
  commentId: Overload:rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose
  href: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.html#rwby_core_gamemodes_training_ui_DummySettingsMainScreen_TryClose_rwby_ui_MenuDirection_System_Boolean_
  name: TryClose
  nameWithType: DummySettingsMainScreen.TryClose
  fullName: rwby.core.gamemodes.training.ui.DummySettingsMainScreen.TryClose
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
