### YamlMime:ManagedReference
items:
- uid: rwby.core.ConfigureDummyCommand
  commentId: T:rwby.core.ConfigureDummyCommand
  id: ConfigureDummyCommand
  parent: rwby.core
  children:
  - rwby.core.ConfigureDummyCommand.Serialize(Photon.Deterministic.BitStream)
  - rwby.core.ConfigureDummyCommand.behaviour
  - rwby.core.ConfigureDummyCommand.blockBehaviour
  - rwby.core.ConfigureDummyCommand.blockDirection
  - rwby.core.ConfigureDummyCommand.controlType
  - rwby.core.ConfigureDummyCommand.counterhit
  - rwby.core.ConfigureDummyCommand.framesBeforeGroundRecovery
  - rwby.core.ConfigureDummyCommand.framesToHoldBlockAfterBlockstunEnded
  - rwby.core.ConfigureDummyCommand.groundRecovery
  - rwby.core.ConfigureDummyCommand.hitsBeforeShouldBlock
  - rwby.core.ConfigureDummyCommand.id
  - rwby.core.ConfigureDummyCommand.throwEscape
  langs:
  - csharp
  - vb
  name: ConfigureDummyCommand
  nameWithType: ConfigureDummyCommand
  fullName: rwby.core.ConfigureDummyCommand
  type: Class
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: ConfigureDummyCommand
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 5
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: 'public class ConfigureDummyCommand : DeterministicCommand'
    content.vb: Public Class ConfigureDummyCommand Inherits DeterministicCommand
  inheritance:
  - System.Object
  - Photon.Deterministic.DeterministicCommand
- uid: rwby.core.ConfigureDummyCommand.id
  commentId: F:rwby.core.ConfigureDummyCommand.id
  id: id
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: id
  nameWithType: ConfigureDummyCommand.id
  fullName: rwby.core.ConfigureDummyCommand.id
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: id
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 7
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public byte id
    return:
      type: System.Byte
    content.vb: Public id As Byte
- uid: rwby.core.ConfigureDummyCommand.controlType
  commentId: F:rwby.core.ConfigureDummyCommand.controlType
  id: controlType
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: controlType
  nameWithType: ConfigureDummyCommand.controlType
  fullName: rwby.core.ConfigureDummyCommand.controlType
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: controlType
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 8
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyControlType controlType
    return:
      type: Quantum.DummyControlType
    content.vb: Public controlType As DummyControlType
- uid: rwby.core.ConfigureDummyCommand.behaviour
  commentId: F:rwby.core.ConfigureDummyCommand.behaviour
  id: behaviour
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: behaviour
  nameWithType: ConfigureDummyCommand.behaviour
  fullName: rwby.core.ConfigureDummyCommand.behaviour
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: behaviour
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 9
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyConfigBehaviour behaviour
    return:
      type: Quantum.DummyConfigBehaviour
    content.vb: Public behaviour As DummyConfigBehaviour
- uid: rwby.core.ConfigureDummyCommand.counterhit
  commentId: F:rwby.core.ConfigureDummyCommand.counterhit
  id: counterhit
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: counterhit
  nameWithType: ConfigureDummyCommand.counterhit
  fullName: rwby.core.ConfigureDummyCommand.counterhit
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: counterhit
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 10
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyConfigCounterhit counterhit
    return:
      type: Quantum.DummyConfigCounterhit
    content.vb: Public counterhit As DummyConfigCounterhit
- uid: rwby.core.ConfigureDummyCommand.blockBehaviour
  commentId: F:rwby.core.ConfigureDummyCommand.blockBehaviour
  id: blockBehaviour
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: blockBehaviour
  nameWithType: ConfigureDummyCommand.blockBehaviour
  fullName: rwby.core.ConfigureDummyCommand.blockBehaviour
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: blockBehaviour
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 11
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyBlockBehaviour blockBehaviour
    return:
      type: Quantum.DummyBlockBehaviour
    content.vb: Public blockBehaviour As DummyBlockBehaviour
- uid: rwby.core.ConfigureDummyCommand.hitsBeforeShouldBlock
  commentId: F:rwby.core.ConfigureDummyCommand.hitsBeforeShouldBlock
  id: hitsBeforeShouldBlock
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: hitsBeforeShouldBlock
  nameWithType: ConfigureDummyCommand.hitsBeforeShouldBlock
  fullName: rwby.core.ConfigureDummyCommand.hitsBeforeShouldBlock
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: hitsBeforeShouldBlock
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 12
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public byte hitsBeforeShouldBlock
    return:
      type: System.Byte
    content.vb: Public hitsBeforeShouldBlock As Byte
- uid: rwby.core.ConfigureDummyCommand.framesToHoldBlockAfterBlockstunEnded
  commentId: F:rwby.core.ConfigureDummyCommand.framesToHoldBlockAfterBlockstunEnded
  id: framesToHoldBlockAfterBlockstunEnded
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: framesToHoldBlockAfterBlockstunEnded
  nameWithType: ConfigureDummyCommand.framesToHoldBlockAfterBlockstunEnded
  fullName: rwby.core.ConfigureDummyCommand.framesToHoldBlockAfterBlockstunEnded
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: framesToHoldBlockAfterBlockstunEnded
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 13
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public byte framesToHoldBlockAfterBlockstunEnded
    return:
      type: System.Byte
    content.vb: Public framesToHoldBlockAfterBlockstunEnded As Byte
- uid: rwby.core.ConfigureDummyCommand.blockDirection
  commentId: F:rwby.core.ConfigureDummyCommand.blockDirection
  id: blockDirection
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: blockDirection
  nameWithType: ConfigureDummyCommand.blockDirection
  fullName: rwby.core.ConfigureDummyCommand.blockDirection
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: blockDirection
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 14
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyBlockDirection blockDirection
    return:
      type: Quantum.DummyBlockDirection
    content.vb: Public blockDirection As DummyBlockDirection
- uid: rwby.core.ConfigureDummyCommand.throwEscape
  commentId: F:rwby.core.ConfigureDummyCommand.throwEscape
  id: throwEscape
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: throwEscape
  nameWithType: ConfigureDummyCommand.throwEscape
  fullName: rwby.core.ConfigureDummyCommand.throwEscape
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: throwEscape
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 15
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyThrowEscape throwEscape
    return:
      type: Quantum.DummyThrowEscape
    content.vb: Public throwEscape As DummyThrowEscape
- uid: rwby.core.ConfigureDummyCommand.groundRecovery
  commentId: F:rwby.core.ConfigureDummyCommand.groundRecovery
  id: groundRecovery
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: groundRecovery
  nameWithType: ConfigureDummyCommand.groundRecovery
  fullName: rwby.core.ConfigureDummyCommand.groundRecovery
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: groundRecovery
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 16
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public DummyGroundRecovery groundRecovery
    return:
      type: Quantum.DummyGroundRecovery
    content.vb: Public groundRecovery As DummyGroundRecovery
- uid: rwby.core.ConfigureDummyCommand.framesBeforeGroundRecovery
  commentId: F:rwby.core.ConfigureDummyCommand.framesBeforeGroundRecovery
  id: framesBeforeGroundRecovery
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: framesBeforeGroundRecovery
  nameWithType: ConfigureDummyCommand.framesBeforeGroundRecovery
  fullName: rwby.core.ConfigureDummyCommand.framesBeforeGroundRecovery
  type: Field
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: framesBeforeGroundRecovery
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 17
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  syntax:
    content: public byte framesBeforeGroundRecovery
    return:
      type: System.Byte
    content.vb: Public framesBeforeGroundRecovery As Byte
- uid: rwby.core.ConfigureDummyCommand.Serialize(Photon.Deterministic.BitStream)
  commentId: M:rwby.core.ConfigureDummyCommand.Serialize(Photon.Deterministic.BitStream)
  id: Serialize(Photon.Deterministic.BitStream)
  parent: rwby.core.ConfigureDummyCommand
  langs:
  - csharp
  - vb
  name: Serialize(BitStream)
  nameWithType: ConfigureDummyCommand.Serialize(BitStream)
  fullName: rwby.core.ConfigureDummyCommand.Serialize(Photon.Deterministic.BitStream)
  type: Method
  source:
    remote:
      path: rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: Serialize
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/QuantumUser/Simulation/mfo/Gamemode/Training/ConfigureDummyCommand.cs
    startLine: 19
  assemblies:
  - Quantum.Simulation
  namespace: rwby.core
  summary: Override this method to add additional data to the command.
  example: []
  syntax:
    content: public override void Serialize(BitStream stream)
    parameters:
    - id: stream
      type: Photon.Deterministic.BitStream
      description: Stream to write and read from
    content.vb: Public Overrides Sub Serialize(stream As BitStream)
  overridden: Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
  overload: rwby.core.ConfigureDummyCommand.Serialize*
references:
- uid: rwby.core
  commentId: N:rwby.core
  href: rwby.html
  name: rwby.core
  nameWithType: rwby.core
  fullName: rwby.core
  spec.csharp:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
  spec.vb:
  - uid: rwby
    name: rwby
    href: rwby.html
  - name: .
  - uid: rwby.core
    name: core
    href: rwby.core.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Photon.Deterministic.DeterministicCommand
  commentId: T:Photon.Deterministic.DeterministicCommand
  parent: Photon.Deterministic
  isExternal: true
  name: DeterministicCommand
  nameWithType: DeterministicCommand
  fullName: Photon.Deterministic.DeterministicCommand
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Photon.Deterministic
  commentId: N:Photon.Deterministic
  isExternal: true
  name: Photon.Deterministic
  nameWithType: Photon.Deterministic
  fullName: Photon.Deterministic
  spec.csharp:
  - uid: Photon
    name: Photon
    isExternal: true
  - name: .
  - uid: Photon.Deterministic
    name: Deterministic
    isExternal: true
  spec.vb:
  - uid: Photon
    name: Photon
    isExternal: true
  - name: .
  - uid: Photon.Deterministic
    name: Deterministic
    isExternal: true
- uid: System.Byte
  commentId: T:System.Byte
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte
  nameWithType: byte
  fullName: byte
  nameWithType.vb: Byte
  fullName.vb: Byte
  name.vb: Byte
- uid: Quantum.DummyControlType
  commentId: T:Quantum.DummyControlType
  parent: Quantum
  href: Quantum.DummyControlType.html
  name: DummyControlType
  nameWithType: DummyControlType
  fullName: Quantum.DummyControlType
- uid: Quantum
  commentId: N:Quantum
  href: Quantum.html
  name: Quantum
  nameWithType: Quantum
  fullName: Quantum
- uid: Quantum.DummyConfigBehaviour
  commentId: T:Quantum.DummyConfigBehaviour
  parent: Quantum
  href: Quantum.DummyConfigBehaviour.html
  name: DummyConfigBehaviour
  nameWithType: DummyConfigBehaviour
  fullName: Quantum.DummyConfigBehaviour
- uid: Quantum.DummyConfigCounterhit
  commentId: T:Quantum.DummyConfigCounterhit
  parent: Quantum
  href: Quantum.DummyConfigCounterhit.html
  name: DummyConfigCounterhit
  nameWithType: DummyConfigCounterhit
  fullName: Quantum.DummyConfigCounterhit
- uid: Quantum.DummyBlockBehaviour
  commentId: T:Quantum.DummyBlockBehaviour
  parent: Quantum
  href: Quantum.DummyBlockBehaviour.html
  name: DummyBlockBehaviour
  nameWithType: DummyBlockBehaviour
  fullName: Quantum.DummyBlockBehaviour
- uid: Quantum.DummyBlockDirection
  commentId: T:Quantum.DummyBlockDirection
  parent: Quantum
  href: Quantum.DummyBlockDirection.html
  name: DummyBlockDirection
  nameWithType: DummyBlockDirection
  fullName: Quantum.DummyBlockDirection
- uid: Quantum.DummyThrowEscape
  commentId: T:Quantum.DummyThrowEscape
  parent: Quantum
  href: Quantum.DummyThrowEscape.html
  name: DummyThrowEscape
  nameWithType: DummyThrowEscape
  fullName: Quantum.DummyThrowEscape
- uid: Quantum.DummyGroundRecovery
  commentId: T:Quantum.DummyGroundRecovery
  parent: Quantum
  href: Quantum.DummyGroundRecovery.html
  name: DummyGroundRecovery
  nameWithType: DummyGroundRecovery
  fullName: Quantum.DummyGroundRecovery
- uid: Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
  commentId: M:Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
  parent: Photon.Deterministic.DeterministicCommand
  isExternal: true
  name: Serialize(BitStream)
  nameWithType: DeterministicCommand.Serialize(BitStream)
  fullName: Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
  spec.csharp:
  - uid: Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Photon.Deterministic.BitStream
    name: BitStream
    isExternal: true
  - name: )
  spec.vb:
  - uid: Photon.Deterministic.DeterministicCommand.Serialize(Photon.Deterministic.BitStream)
    name: Serialize
    isExternal: true
  - name: (
  - uid: Photon.Deterministic.BitStream
    name: BitStream
    isExternal: true
  - name: )
- uid: rwby.core.ConfigureDummyCommand.Serialize*
  commentId: Overload:rwby.core.ConfigureDummyCommand.Serialize
  href: rwby.core.ConfigureDummyCommand.html#rwby_core_ConfigureDummyCommand_Serialize_Photon_Deterministic_BitStream_
  name: Serialize
  nameWithType: ConfigureDummyCommand.Serialize
  fullName: rwby.core.ConfigureDummyCommand.Serialize
- uid: Photon.Deterministic.BitStream
  commentId: T:Photon.Deterministic.BitStream
  parent: Photon.Deterministic
  isExternal: true
  name: BitStream
  nameWithType: BitStream
  fullName: Photon.Deterministic.BitStream
