### YamlMime:ManagedReference
items:
- uid: rwby.SettingsManager.SettingsChangedEvent
  commentId: T:rwby.SettingsManager.SettingsChangedEvent
  id: SettingsManager.SettingsChangedEvent
  parent: rwby
  children: []
  langs:
  - csharp
  - vb
  name: SettingsManager.SettingsChangedEvent
  nameWithType: SettingsManager.SettingsChangedEvent
  fullName: rwby.SettingsManager.SettingsChangedEvent
  type: Delegate
  source:
    remote:
      path: rwbyq_unity/Assets/1.Project/Scripts/System/SettingsManager.cs
      branch: dev
      repo: https://ChrisTides11@dev.azure.com/ChrisTides11/rwbyq/_git/rwbyq
    id: SettingsChangedEvent
    path: ../../../Unity/rwbyq/rwbyq_unity/Assets/1.Project/Scripts/System/SettingsManager.cs
    startLine: 12
  assemblies:
  - rwby
  namespace: rwby
  syntax:
    content: public delegate void SettingsManager.SettingsChangedEvent(SettingsManager settingsManager)
    parameters:
    - id: settingsManager
      type: rwby.SettingsManager
    content.vb: Public Delegate Sub SettingsManager.SettingsChangedEvent(settingsManager As SettingsManager)
references:
- uid: rwby
  commentId: N:rwby
  href: rwby.html
  name: rwby
  nameWithType: rwby
  fullName: rwby
- uid: rwby.SettingsManager
  commentId: T:rwby.SettingsManager
  parent: rwby
  href: rwby.SettingsManager.html
  name: SettingsManager
  nameWithType: SettingsManager
  fullName: rwby.SettingsManager
